Add CC-specific information to value metadata
AlCalzone/node-zwave-js pull request #1141
Opened 2020-11-23 17:02 UTC by AlCalzone

fixes: #1137
by adding an optional `ccSpecific` field to the value metadata.

Checklist:

- [x] AlarmSensor (base type `AlarmSensorValueMetadata`)
- [ ] BinarySensor
- [ ] Meter
- [ ] MultilevelSensor
- [ ] MultilevelSwitch
- [ ] ThermostatMode
- [ ] ThermostatOperatingState
- [ ] ThermostatSetpoint

2020-11-23 18:50 UTC, AlCalzone commented
@robertsLando let me know if this solves your issues :)

2020-11-23 19:28 UTC, robertsLando commented
Tomorrow, thanks so much! 😍

2020-11-24 09:17 UTC, robertsLando commented
@AlCalzone What about adding some docs about this? I have added the required changes but unfortunally I haven't any device to test this, will let user to try this in https://github.com/zwave-js/zwavejs2mqtt/pull/20

2020-11-24 09:19 UTC, AlCalzone commented
> What about adding some docs about this?

Yeah... metadata is not documented at all 😅

2020-11-24 09:27 UTC, robertsLando commented
I could do it for you :) You have too much work to do here

2020-11-24 10:17 UTC, AlCalzone commented
FFS... `lerna`, `npm workspaces` and `npm ci` don't like each other...

2020-11-24 13:37 UTC, robertsLando submitted a review, later dismissed
LGTM

2020-11-24 15:11 UTC, robertsLando requested changes
Also I would add a link to this section in `getValueMetadata` function

2020-11-24 15:11 UTC, robertsLando commented on docs/api/valueid.md
> +-   `states`: Human-readable names for numeric values
Maybe add an example of a state here?

2020-11-24 15:11 UTC, robertsLando commented on docs/api/valueid.md
> +	/** The maximum length this string may have (optional) */
```suggestion
```

2020-11-24 15:11 UTC, robertsLando commented on docs/api/valueid.md
> +	/** The default value */
```suggestion
```

2020-11-24 15:11 UTC, robertsLando commented on docs/api/valueid.md
> +		sensorType: number;
We could  add a link to sensortypes.json ?

2020-11-24 15:11 UTC, robertsLando commented on docs/api/valueid.md
> +		meterType: number;
Link to meter types json?

2020-11-24 15:12 UTC, robertsLando commented on docs/api/valueid.md
> +		sensorType: number;
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/sensorTypes.json

2020-11-24 15:12 UTC, robertsLando commented on docs/api/valueid.md
> +		meterType: number;
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/meters.json

2020-11-24 15:13 UTC, AlCalzone commented
> `getValueMetadata`

In the method implementation itself or where do you mean?

2020-11-24 15:16 UTC, robertsLando commented
> Every value in Z-Wave has associated metadata that defines the range of allowed values etc. You can retrieve this metadata using getValueMetadata. Like getValue this takes a single argument of the type ValueMetadata <--- HERE

2020-11-24 15:22 UTC, robertsLando reviewed
Should we reference somewhere in docs also indicators.json notifications.json and scales?

2020-11-24 15:29 UTC, AlCalzone commented
I've referenced the scales. Notifications and Indicators might be good to add here too

2020-11-24 15:44 UTC, robertsLando approved these changes
LGTM :tada:

2020-11-24 15:50 UTC, merged