Add Technisat Dimmer and series switch
AlCalzone/node-zwave-js pull request #1252
Opened 2020-12-25 19:00 UTC by fanningert

Hello, I added a configuration for Technisat dimmer and Technisat series switch. Please merge.

2020-12-25 19:40 UTC, roflmao commented
Need index.json update as well

2020-12-25 20:17 UTC, fanningert commented
Thank you, I missed it. But now added.

2020-12-27 15:00 UTC, AlCalzone requested changes
Thanks, I found a few things that need to be changed though.

FYI, you can automatically update the index file and check your config files like this:
https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=contributing-configuration-files

2020-12-27 17:05 UTC, fanningert commented on packages/config/config/devices/0x0299/1a91.json
> +			"label": "Parameter 2",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Serienschalter.pdf

2020-12-27 17:05 UTC, fanningert commented on packages/config/config/devices/0x0299/1a91.json
> +			"label": "Parameter 3",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Serienschalter.pdf

2020-12-27 17:11 UTC, fanningert commented on packages/config/config/devices/0x0299/1a91.json
> +			"label": "Parameter 1",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Serienschalter.pdf

2020-12-27 17:12 UTC, fanningert commented on packages/config/config/devices/0x0299/1a91.json
> +			"minValue": 0,
Is corrected

2020-12-27 17:12 UTC, fanningert commented on packages/config/config/devices/0x0299/1a91.json
> +			"valueSize": 2,
Is corrected

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"description": "Enable/disable central scene notifications for 2x-5x button presses.",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"label": "Parameter 2",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"label": "Parameter 3",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"label": "Parameter 4",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"label": "Parameter 5",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:14 UTC, fanningert commented on packages/config/config/devices/0x0299/1a92.json
> +			"label": "Parameter 6",
It's the same name that the manufacturer used in the manual.
Sorry, they have only a German manual
https://www.technisat.com/assets/medias/docus/130/BDA_Dimmer.pdf

2020-12-27 17:16 UTC, fanningert commented
@AlCalzone thanks. I will check the link. Sorry for the manuell work. Ich will test ist with the tool.

2020-12-27 17:46 UTC, AlCalzone commented
> Looks like I need the create the right enviroment for this test

You probably need to execute `yarn` in the local repo to install all missing dependencies.

2020-12-27 18:01 UTC, fanningert commented
@AlCalzone Thanks, that's help in the steps. But at the end I also get an error. Witch OS version are you using. I am using Fedora 33 (XFCE Spin). Looks like it's not the perfect for this task. Is the current version of this Pull Request correct?

```bash
$ yarn run config import -i
yarn run v1.22.5
$ ts-node maintenance/importConfig.ts import -i
Error: Cannot find module '/home/fanningert/Dokumente/github/node-zwave-js/packages/config/node_modules/@zwave-js/core/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fanningert/Dokumente/github/node-zwave-js/packages/config/src/DeviceClasses.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/home/fanningert/Dokumente/github/node-zwave-js/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2020-12-27 18:57 UTC, AlCalzone commented
Just running yarn should install all missing dependencies. Manually installing them will mess up the local symlinks, especially this:

    # Add missing libraries
    $ npm install -D typescript
    $ npm install -D ts-node
    $ npm install -D @zwave-js/core
    $ npm install -D @zwave-js/shared

To clean up, run

    rm -rf node_modules && yarn

2020-12-27 19:03 UTC, fanningert commented
Sorry, but I get an error at the end.

```bash
$ git clone ...
$ cd node-zwave-js
$ rm -rf node_modules && yarn 
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.2.1: The platform "linux" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @xstate/test@0.4.1" has unmet peer dependency "xstate@^4.9.0".
warning "@xstate/test > @xstate/graph@1.3.0" has unmet peer dependency "xstate@^4.9.0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
[4/4] Building fresh packages...
Done in 24.83s.
$ yarn run config import -i
yarn run v1.22.5
$ ts-node maintenance/importConfig.ts import -i

/home/fanningert/Dokumente/github/node-zwave-js/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/config/src/DeviceClasses.ts:1:61 - error TS2307: Cannot find module '@zwave-js/core' or its corresponding type declarations.

1 import { CommandClasses, ZWaveError, ZWaveErrorCodes } from "@zwave-js/core";
                                                              ~~~~~~~~~~~~~~~~
packages/config/src/DeviceClasses.ts:2:37 - error TS2307: Cannot find module '@zwave-js/shared' or its corresponding type declarations.

2 import { JSONObject, num2hex } from "@zwave-js/shared";
                                      ~~~~~~~~~~~~~~~~~~
packages/config/src/DeviceClasses.ts:100:4 - error TS2571: Object is of type 'unknown'.

100  		e.code === ZWaveErrorCodes.Config_Invalid
     		~
packages/config/src/DeviceClasses.ts:105:39 - error TS2571: Object is of type 'unknown'.

105  				`Could not load scales config: ${e.message}`,
     				                                 ~

    at createTSError (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/xxx/github/node-zwave-js/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2020-12-28 11:39 UTC, AlCalzone commented
> I get an error at the end.

Weird, it works for me:

```
domin@DESKTOP-OCULUR0 MINGW64 /c/Repositories/node-zwave-js (pr/fanningert/1252)
$ yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.2.1: The platform "win32" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @xstate/test@0.4.1" has unmet peer dependency "xstate@^4.9.0".
warning "@xstate/test > @xstate/graph@1.3.0" has unmet peer dependency "xstate@^4.9.0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
[4/4] Building fresh packages...
Done in 13.07s.

domin@DESKTOP-OCULUR0 MINGW64 /c/Repositories/node-zwave-js (pr/fanningert/1252)
$ yarn run config import -i
yarn run v1.22.5
$ ts-node maintenance/importConfig.ts import -i
Done in 3.73s.
```

I'm on Windows, but also develop in a debian container. Maybe you need to run `yarn run build` once before the import script.

2020-12-28 11:40 UTC, AlCalzone approved these changes

2020-12-28 11:40 UTC, merged