Update ZDB5100 config to expand on parameter 1
AlCalzone/node-zwave-js pull request #1424
Opened 2021-01-16 21:39 UTC by LordMike

2021-01-16 21:40 UTC, LordMike commented
@zwave-js-bot semantic?

2021-01-16 23:44 UTC, AlCalzone commented
Why the hell is this PR failing?

2021-01-16 23:45 UTC, AlCalzone commented
@zwave-js-bot rename commit

2021-01-17 00:22 UTC, AlCalzone commented
Okay, there was an error getting swallowed...

2021-01-17 00:52 UTC, AlCalzone requested changes

2021-01-17 00:52 UTC, AlCalzone commented on packages/config/config/devices/0x0234/zdb5100.json
> +			"label": "Pusbutton 1 controls the dimmer",
```diff
- Pusbutton
+ Pushbutton
```
(same for the other params)

2021-01-17 00:52 UTC, AlCalzone commented on packages/config/config/devices/0x0234/zdb5100.json
> +			"description": "Enabling this parameter, lets pushbutton 1 control the built-in dimmer.",
I think the comma behind `parameter` does not belong there. (same for the other params)

2021-01-17 17:36 UTC, merged