feat(config): support Zooz ZEN34, ZEN76, and ZEN77
AlCalzone/node-zwave-js pull request #1494
Opened 2021-01-25 16:50 UTC by mattstocum

Adds support for new Zooz ZEN34, ZEN76, and ZEN77 switches.

2021-01-25 16:51 UTC, AlCalzone commented
/cc @blhoward2 to avoid conflicts

2021-01-25 16:54 UTC, mattstocum commented
These devices are not yet listed on products.z-wavealliance.org, so hopefully there won't be any conflicts. The association groups do not seem to be documented anywhere publicly, but I did confirm them with Zooz support.

2021-01-25 17:03 UTC, blhoward2 commented
No concerns, then. Did their support confirm everything? For whatever reason they don’t list their devices and whoever makes it for them sometimes does. I debated emailing them to see if they could send them en masse.

2021-01-25 17:08 UTC, AlCalzone requested changes

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen76.json
> +			"defaultValue": 0,
Add `"unit": "minutes"` please

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen76.json
> +			"defaultValue": 0,
Add `"unit": "minutes"` please

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen76.json
> +			"maxValue": 3,
```suggestion
			"maxValue": 2,
```
?

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen76.json
> +			"maxValue": 2,
```suggestion
			"maxValue": 1,
```
?

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen77.json
> +			"defaultValue": 0,
Add `"unit": "minutes"` please

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen77.json
> +			"defaultValue": 0,
Add `"unit": "minutes"` please

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen77.json
> +			"defaultValue": 1,
Add `"unit": "seconds"` please

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen77.json
> +			"maxValue": 3,
2?

2021-01-25 17:08 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen77.json
> +			"defaultValue": 5,
Add `"unit": "seconds"` please

2021-01-25 19:51 UTC, mattstocum commented
I think I got everything resolved. Sorry if the multiple commits are an issue, I know just enough git to get myself in to trouble and make a mess of commit history.

2021-01-25 19:55 UTC, mattstocum commented
> No concerns, then. Did their support confirm everything? For whatever reason they don’t list their devices and whoever makes it for them sometimes does. I debated emailing them to see if they could send them en masse.

I got the config parameters for the 76 and 77 from https://www.support.getzooz.com/kb/article/549-zen76-s2-on-off-switch-700-advanced-settings/ and https://www.support.getzooz.com/kb/article/550-zen77-s2-dimmer-700-advanced-settings/. For the Zen34 I got everything from the manual.

I think the Zen26 and 27 have also been updated to have some of the new parameters that the 76 and 77 have with the 3.x firmware, but the online documentation hasn't been updated accordingly, but I haven't had time to test everything.

2021-01-25 19:56 UTC, AlCalzone commented
> Sorry if the multiple commits are an issue

Not at all, I'm squash-merging every PR.

@blhoward2 let me know if your concerns are resolved, then I'll merge.

2021-01-25 20:08 UTC, blhoward2 commented
@AlCalzone I'm good

2021-01-25 20:35 UTC, merged

2021-02-12 21:49 UTC, anatwick commented
I have been working with the guys over on discord with a Zooz Zen34 and there seems to be an issue with double tap's on the switch.  It reports it as central scene and a "double tap" triggers any automation set for the single tap.   Not sure exactly if i need to do something different for this or if it is some sort of bug.

2021-02-12 21:51 UTC, anatwick commented
When listening for the command it appears to only recognize the first tap and nothing else  here is the automation yaml i was attempting for a double tap:    
alias: Millies Bed Switch - Test Double Tap On
description: ''
trigger:
  - event_data:
      node_id: 62
      property_key_name: '001'
      value: KeyPressed2x
    event_type: zwave_js_event
    platform: event
condition: []
action:
  - scene: scene.office_lights_test_2
mode: single

2021-02-12 23:40 UTC, blhoward2 commented
Please open a bug report so we can look into it. PRs are not the proper forum for troubleshooting.