feat: add manual links to device files
AlCalzone/node-zwave-js pull request #1584
Opened 2021-02-04 04:14 UTC by blhoward2

Closes #1551. @marcus-j-davies

2021-02-04 04:15 UTC, blhoward2 commented
@zwave-js-bot fix lint

2021-02-04 07:08 UTC, blhoward2 commented
@AlCalzone These should be ready to merge. The only change is adding the manual link, and anything else that normalizeConfig() caught.

2021-02-04 07:29 UTC, robertsLando commented
Nice!! :)

2021-02-04 07:41 UTC, AlCalzone requested changes
Please check the other changes that they don't introduce errors like the two I found. The other diffs are not expanded on GitHub and I currently don't have time to open every one by hand.

2021-02-04 07:41 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgpb101.json
> +			"minValue": 99,
Uh I think these are a mistake

2021-02-04 07:41 UTC, AlCalzone commented on packages/config/config/devices/0x0131/ne_nas_ab02z.json
> +			"minValue": 255,
Also this

2021-02-04 14:21 UTC, blhoward2 commented
I'm just going to revert and re-run without the normalizeConfig for now. I don't have time to go through them all either.

2021-02-05 02:29 UTC, blhoward2 commented
@zwave-js-bot fix lint

2021-02-05 02:30 UTC, blhoward2 commented
@AlCalzone If you can invoke the bot, these are ready to merge. I did a complete revert and removed the normalizeConfig, so we're only adding the manual link and then writing back.

2021-02-05 07:12 UTC, AlCalzone commented
@zwave-js-bot fix lint

2021-02-08 02:18 UTC, blhoward2 reviewed
Ready to go

2021-02-08 08:32 UTC, AlCalzone submitted a review, later dismissed

2021-02-08 08:32 UTC, AlCalzone commented on packages/config/config/devices/0x0131/ne_nas_ab02z.json
> +			"minValue": 0,
We don't have an option for 0

2021-02-08 08:32 UTC, AlCalzone commented on packages/config/config/devices/0x0131/ne_nas_ab02z.json
> +			"minValue": 0,
dito

2021-02-09 08:18 UTC, AlCalzone approved these changes

2021-02-09 08:19 UTC, merged