Add MP21Z Support
AlCalzone/node-zwave-js pull request #1598
Opened 2021-02-04 21:15 UTC by highaltidude

2021-02-04 21:22 UTC, AlCalzone requested changes

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +  }
comma missing

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +      "description": "Count Down Configuration",
If the description does not add value, better remove it.

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +      "description": "Count Down Configuration",
Or maybe there's a better explanation for this param?

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +      "maxValue": "32767",
Is there a unit for these values?

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +		"reset": "Power off MP21Z keep holding the PROG button Power on,Press and keep \n holding the PROG button for no less than 10 seconds. Please use this procedure \n only when the network primary con
These could use some cleaning (remove the unnecessary \n, add missing space after ",")

2021-02-04 21:22 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21z.json
> +      }
Please make this consistent (same casing for on/off and LED everywhere)

2021-02-04 21:39 UTC, highaltidude commented
@zwave-js-bot fix lint

2021-02-04 21:43 UTC, highaltidude reviewed
Edits requested should be resolved.

2021-02-04 21:43 UTC, highaltidude commented on packages/config/config/devices/0x0312/mp21z.json
> +      "maxValue": "32767",
added unit

2021-02-04 22:51 UTC, AlCalzone commented
@zwave-js-bot fix lint

2021-02-04 22:54 UTC, AlCalzone approved these changes, later dismissed

2021-02-04 22:54 UTC, AlCalzone commented
Thanks, will merge once tests are through

2021-02-04 23:16 UTC, AlCalzone commented
well... looks like you found a bug in my checks :D
Fixed both the checks and the file.

2021-02-04 23:23 UTC, merged

2021-04-01 14:42 UTC, Papester commented
It seems the status indicator config option is reversed as described at https://devices.zwave-js.io/?jumpTo=0x0312:0xff00:0xff0c:1.0#

Options:
    0: LED on when load off, LED off when load on (actually is LED on when load on, LED off when load off)
    1: LED on when load on, LED off when load off (actually is  LED on when load off, LED off when load on)
    2: LED always off

Using Z-Wave JS to MQTT Current version: 0.9.1 and Z-Wave JS Current version: 0.1.16

2021-04-01 14:48 UTC, AlCalzone commented
Can you open a PR with the change please? The device browser should point you to the correct file.