feat(config): add support for Yale YRM276 lock
AlCalzone/node-zwave-js pull request #1599
Opened 2021-02-04 21:22 UTC by natekspencer

Adds support for the Yale Assure Lock for Andersen Patio Doors model YRM276.

Config was imported from OZW file which I had created for that project.

2021-02-04 21:47 UTC, AlCalzone requested changes

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "1 to 180 seconds (default is 30)",
```suggestion
```
Doesn't add any value over the other properties

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "3 to 10 (default is 5)",
```suggestion
```

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +				},
Aside from the fact that the description is not meant for default values, the description seems to contradict the defaultValue

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "10 to 180 seconds (default is 60)",
remove please

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Normal (default)\nVacation = keypad lockout\nPrivacy = no keypad, RF Unlock will work",
```suggestion
			"description": "Normal (default); Vacation = keypad lockout; Privacy = no keypad, RF Unlock will work",
```
I'm kinda okay with this - but please no newlines.

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Default is On",
nope :)

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Default is Off",
nope, just remove all unnecessary descriptions please

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			]
This is difficult... minValue should be 0 (or defaultValue is out of range). And I'd add an option for 0, which does nothing.

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "10 to 2540 second. This value is represented as seconds X 10 (ie a value of 4 would mean a door propped timer of 40 seconds). Set to 0 to disable (default).\n\n**Optional Door Posi
```suggestion
			"description": "Set to 0 to disable. **Optional Door Position Switch must have been installed with the lock.",
```

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"unit": "seconds",
```suggestion
			"unit": "10 seconds",
```
not too nice, but that's how it is.

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Used to enable/disable door condition alarms for locks that support a door position sensor. Any lock that does not support DPS will always report Off. Default is Off\n\n**Optional
```suggestion
			"description": "Used to enable/disable door condition alarms for locks that support a door position sensor. Any lock that does not support DPS will always report Off. **Optional Door Position Switch must have been installed with the lock.",
```

2021-02-04 21:47 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Off (default) = The lock will always lock regardless of DPSstate\nOn = Check DPS before motorized lock function\n\n**Optional Door Position Switch must hvae been installed with the
```suggestion
			"description": "Off = The lock will always lock regardless of DPS state; On = Check DPS before motorized lock function. **Optional Door Position Switch must hvae been installed with the lock.",
```

2021-02-08 05:31 UTC, blhoward2 commented
@AlCalzone I just pushed fixes myself to get this moved along given the number we have open.

2021-02-08 05:32 UTC, blhoward2 approved these changes, later dismissed
Made by @blhoward2

2021-02-08 05:37 UTC, natekspencer commented
Thanks for updating those for me @blhoward2!

2021-02-08 05:38 UTC, natekspencer commented
I fixed a couple of spelling errors, looks like that rejected your review. Oops, sorry :-/

2021-02-08 05:40 UTC, blhoward2 approved these changes, later dismissed
Approved

2021-02-08 05:50 UTC, blhoward2 commented
@AlCalzone Ready to merge

2021-02-08 08:30 UTC, AlCalzone requested changes

2021-02-08 08:30 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"label": "Wrong Code Lockout Time",
I think we should use this parameter definition in the other yale file I just reviewed - this seems better!

2021-02-08 08:30 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> -			"description": "Normal (default)\nVacation = keypad lockout\nPrivacy = no keypad, RF Unlock will work",
I think the description is okay - it offers additional info what the options do.

2021-02-08 08:30 UTC, AlCalzone commented on packages/config/config/devices/0x0129/yrm276.json
> +			"description": "Note: Optional Door Position Switch must hvae been installed with the lock.",
```suggestion
			"description": "Note: Optional Door Position Switch must have been installed with the lock.",
```

2021-02-08 23:09 UTC, AlCalzone approved these changes

2021-02-08 23:09 UTC, AlCalzone commented
Thanks!

2021-02-08 23:09 UTC, merged