fix(config): mco home config files for v5 devices
AlCalzone/node-zwave-js pull request #1696
Opened 2021-02-10 18:12 UTC by jcam

This adds support for the following v5 mco home devices:
MH-C421 - Shutters (cover device)
MH-DT411 - gen5 touch dimmer
MH-S314 - gen5 4 button touch switch
MH-S411 - gen5 1 button touch switch
MH-S412 - gen5 2 button touch switch

2021-02-11 03:29 UTC, blhoward2 requested changes
Looking great!

2021-02-11 03:29 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-c421.json
> +			"label": "Demo Trip and Auto Calibration",
Any idea what this is that we could describe in a description?

2021-02-11 03:29 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-s314-1502.json
> +			"label": "Basic CC Integration Setting",
Any idea what this is, or what the modes do? Can we make these labels more descriptive? Add a description to the parameter if not? I am only marking things once so please carry through.

2021-02-11 03:29 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-s411-1502.json
> +			"defaultValue": 0,
Is there a unit we can put here? I think there are some others like this.

2021-02-11 03:29 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-s411-1502.json
> +			"description": "See Manual",
As above. Can we make the label descriptive? Add a description? (If not, delete the See manual description)

2021-02-11 03:33 UTC, blhoward2 requested changes
Forgot a couple. Note that there are lint errors for two of the parameters that need to be unsigned.

2021-02-11 03:33 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-c421.json
> +			"maxValue": 98,
Is this really 98 and not 99?

2021-02-11 03:33 UTC, blhoward2 commented on packages/config/config/devices/0x015f/mh-s314.json
>  			"description": "85 restore factory setting",
This doesn't make sense. 85 isn't allowed within the range. Could you verify? Usually we add an option that says Normal Operation and value 0 (that does nothing), then add an option with the reset value.

2021-02-11 13:04 UTC, jcam commented on packages/config/config/devices/0x015f/mh-c421.json
> +			"maxValue": 98,
yep

2021-02-11 18:38 UTC, blhoward2 submitted a review, later dismissed
Looks good to me. Please request a review from @AlCalzone so he can give final approval and merge.

2021-02-11 19:18 UTC, jcam commented
Oddly, I can't request a review. But I imagine he'll see your comment tagging him :)

2021-02-11 19:41 UTC, blhoward2 commented
You can’t request a review at the top under Reviewers?

On Thu, Feb 11, 2021 at 2:19 PM Jesse Campbell <notifications@github.com>
wrote:

> Oddly, I can't request a review. But I imagine he'll see your comment
> tagging him :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zwave-js/node-zwave-js/pull/1696#issuecomment-777727285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIAOCTQI6MOJUDL4XMO6VITS6QUS5ANCNFSM4XNNOSTA>
> .
>

2021-02-11 23:23 UTC, AlCalzone requested changes

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-c421.json
> +			"label": "KWH Meter Report Period",
```suggestion
			"label": "kWh Meter Report Period",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-c421.json
> +			"label": "LED BackLight Brightness",
```suggestion
			"label": "LED Backlight Brightness",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"label": "Energy Meter Report KWH",
```suggestion
			"label": "Energy Meter Report kWh",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.01A",
```suggestion
			"unit": "0.01 A",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.1V",
```suggestion
			"unit": "0.1 V",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.1W",
```suggestion
			"unit": "0.1 W",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.01A",
```suggestion
			"unit": "0.01 A",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.1V",
```suggestion
			"unit": "0.1 V",
```

2021-02-11 23:23 UTC, AlCalzone commented on packages/config/config/devices/0x015f/mh-dt311_411.json
> +			"unit": "0.1W",
```suggestion
			"unit": "0.1 W",
```
Please check the other units too :)

2021-02-12 07:52 UTC, AlCalzone approved these changes

2021-02-12 07:53 UTC, merged