feat(config): updated params for LZW31-SN and LZW31
AlCalzone/node-zwave-js pull request #1739
Opened 2021-02-12 17:53 UTC by Hilo4321

correcting requested changes from #1700

2021-02-13 11:48 UTC, Petro31 requested changes
Remove the comments an it will pass lint.  They aren't needed anyways

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-bsd_0.0-1.45.json
> +// Black Series Dimmer
Remove comments to pass lint

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-bsd_1.47-1.47.json
> +// Black Series Dimmer
Same

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-bsd_1.49.json
> +// Black Series Dimmer
same

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-sn_0.0-1.45.json
> +// Inovelli LZW31-SN
same

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-sn_1.47-1.47.json
> +// Red Series Dimmer
same

2021-02-13 11:48 UTC, Petro31 commented on packages/config/config/devices/0x031e/lzw31-sn_1.49.json
> +// Red Series Dimmer
same

2021-02-13 13:50 UTC, AlCalzone commented
The comments shouldn't affect linting.
@zwave-js-bot fix lint

2021-02-13 15:41 UTC, AlCalzone commented
Hmm guess there was a space at the end

2021-02-13 15:59 UTC, Petro31 commented
> The comments shouldn't affect linting.
> @zwave-js-bot fix lint

Odd, when I was running lint, that was the only thing that was failing.  My bad!

2021-02-14 17:44 UTC, AlCalzone commented
I think this was superseded by #1740, right?

2021-02-14 17:57 UTC, Hilo4321 commented
> I think this was superseded by #1740, right?

I think these are actually the same.

2021-02-14 17:57 UTC, closed without merging