fix: correct heatit brand names
AlCalzone/node-zwave-js pull request #1776
Opened 2021-02-16 04:32 UTC by blhoward2

2021-02-16 07:31 UTC, AlCalzone requested changes

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/4512689.json
> +	"manufacturer": "THeatit",
```suggestion
	"manufacturer": "Heatit",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/4512688.json
>  	"label": "4512688",
I'd put Z-Smoke and similar in the labels

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z-relay.json
> +			"description": "This parameter decides which kind of thermistor that is connected to the input..",
```suggestion
			"description": "This parameter decides which kind of thermistor is connected to input 1.",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z-relay.json
> +			"description": "This parameter decides which kind of thermistor that is connected to the input.",
```suggestion
			"description": "This parameter decides which kind of thermistor is connected to input 2.",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z-relay.json
> +			"description": "Configures the state that will cause the relay to be turned on",
```suggestion
			"description": "Configures which events will cause the relay to be turned on",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z-relay.json
> +			"description": "Configures the state that will cause the relay to be turned off",
```suggestion
			"description": "Configures which events will cause the relay to be turned off",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z_push_button_8.json
> +	"label": " Z Push Button 8",
```suggestion
	"label": "Z Push Button 8",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z_water.json
>  			"description": "This parameter decides which kind of thermistor that is connected to the input..",
see previous file (same for the next labels)

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z_water.json
> +			"unit": "seconds",
```suggestion
			"unit": "10 seconds",
```

2021-02-16 07:31 UTC, AlCalzone commented on packages/config/config/devices/0x019b/heatit_z_water.json
> +			"unit": "seconds",
when I go by the option description. Might affect all these parameters

2021-02-18 07:17 UTC, AlCalzone approved these changes

2021-02-18 07:17 UTC, AlCalzone commented
ready?

2021-02-18 12:46 UTC, blhoward2 commented
Should be

2021-02-18 13:18 UTC, merged