fix(cc): update SceneControllerConfigurationCC API for get / getLastActivated
AlCalzone/node-zwave-js pull request #1834
Opened 2021-02-20 01:26 UTC by Ikcelaks

This PR updates the SceneControllerConfigurationCC API to follow the decisions we made while working on the SceneActuatorConfigurationCC API.

I also applied a few of the other refinements:

1. Set no longer schedules a Poll.
2. `PhysicalCCAPI` was changed to CCAPI, because the Set command is allowed to be part of a Multicast. (and related changes)
3. Prevented Reports with `groupId = 0` from being persisted.

2021-02-21 01:31 UTC, AlCalzone commented
>     1. Set no longer schedules a Poll.

Forgot to push that?
![grafik](https://user-images.githubusercontent.com/17641229/108612894-dd776e80-73ec-11eb-9255-88c3115d9c0e.png)

2021-02-21 01:33 UTC, AlCalzone requested changes
Other than the refresh thing this looks good

2021-02-21 04:27 UTC, Ikcelaks commented
> > ```
> > 1. Set no longer schedules a Poll.
> > ```
> 
> Forgot to push that?
> ![grafik](https://user-images.githubusercontent.com/17641229/108612894-dd776e80-73ec-11eb-9255-88c3115d9c0e.png)

I think I just missed that I was polling in both the `SET_VALUE` and `set()` functions.  I did an actual search this time.

2021-02-22 20:55 UTC, AlCalzone approved these changes

2021-02-22 20:56 UTC, merged