feat(config): add config for Ring Range Extender
AlCalzone/node-zwave-js pull request #1924
Opened 2021-03-01 06:09 UTC by WizKid

Tested it with firmware version 1.7 and 2.4 with the US version of the extender.

Those where the only version of the firmware I could get my hands on. So it is possible that the extra parameters was added earlier than 2.4 but I can't check that.

2021-03-01 08:05 UTC, AlCalzone requested changes

2021-03-01 08:05 UTC, AlCalzone commented on packages/config/config/devices/0x0346/range_extender_gen1.json
> +			"description": "Default heartbeat check in time",
```suggestion
```

2021-03-01 08:05 UTC, AlCalzone commented on packages/config/config/devices/0x0346/range_extender_gen1.json
> +			"description": "The number of seconds waiting for a supervision report in response to a supervision get from the sensor",
```suggestion
			"description": "How long to wait for a supervision report in response to a supervision get from the sensor",
```

2021-03-01 08:05 UTC, AlCalzone commented on packages/config/config/devices/0x0346/range_extender_gen1.json
> +			"description": "Number of application level retries attempted for messages either not ACKed or messages encapsulated via supervision get that did not receive a report",
```suggestion
			"description": "Number of application level retries attempted for messages either not ACKed or Supervision encapsulated messages that did not receive a report",
```

2021-03-01 08:05 UTC, AlCalzone commented on packages/config/config/devices/0x0346/range_extender_gen1.json
> +			"description": "The number base seconds used in the calculation for sleeping between retry messages",
```suggestion
			"description": "Used to calculate the delay between retried messages",
```

2021-03-01 08:05 UTC, AlCalzone commented on packages/config/config/devices/0x0346/range_extender_gen1.json
> +			"label": "Supervision Battery Report (one in N)",
```suggestion
			"label": "Supervision Battery Report Frequency",
```

2021-03-01 20:52 UTC, AlCalzone approved these changes
LGTM unless @blhoward2 has something to add?

2021-03-02 00:47 UTC, blhoward2 approved these changes

2021-03-02 07:09 UTC, merged