Neo CoolCam NAS-WR01ZE V2
AlCalzone/node-zwave-js pull request #2028
Opened 2021-03-09 21:45 UTC by Masterz69

Based on information in issue #1221 about NAS-WR01ZE firmware V2, as well as checked with my owned plug manuals.

2021-03-10 15:22 UTC, AlCalzone commented
I'm a bit confused - are the WR01Z and WR01ZE different devices?

2021-03-11 09:56 UTC, Masterz69 commented
As per openzwave.com - see links in #1221:

   <MetaDataItem id="1027" name="Identifier" type="0200">NAS-WR01ZE</MetaDataItem>
    <MetaDataItem id="1027" name="Identifier" type="0100">NAS-WR01ZE</MetaDataItem>
    <MetaDataItem id="1027" name="FrequencyName" type="0100">U.S. / Canada / Mexico</MetaDataItem>
    <ChangeLog>
      <Entry author="David Burrows - david@burrows.org" date="19 Aug 2020" revision="2">Added metadata, and added US version (type 0100) that is branded "Power Plug" with no model number displayed. There is no matching Z-Wave Alliance database entry.</Entry>
    </ChangeLog>


0258:1027:0200 comparing with 0258:0087:0003 - parameters in different order.

2021-03-11 10:08 UTC, AlCalzone commented
I don't trust the OZW database anymore. So these are two different devices with just a very similar name?
Google search doesn't help much.

2021-03-11 11:09 UTC, Masterz69 commented
Sure, see no clear picture too.

Me and @jghaanstra have on hands devices 0258:1027:0200.
They have same parameter as 0258:0087:0003, but in different order.

ZWave alliance database contains https://products.z-wavealliance.org/products/1783
^^ NAS-WR01Z == 0258:0087:0003 - w/out E letter.

And no ZE model in products.z-wavealliance.org 
- may be Chinese manufacturing something with finished certification/approval ?

2021-03-11 11:56 UTC, AlCalzone commented
Ok we can treat the ZE as the new revision then. Makes sense.

I'll review the change itself later, will let you know.

2021-03-12 16:15 UTC, AlCalzone requested changes

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "This parameter defines the LED indication Function ON/OFF.",
```suggestion
			"label": "LED Indication",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"unit": "percentage",
```suggestion
			"unit": "%",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "Power consumed change to be reported",
```suggestion
			"description": "Change in power consumption that triggers a report",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "Plug state after power-on",
```suggestion
			"label": "Remember Relay ON/OFF status after power failure",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			]
```suggestion
			"options": [
				{
					"label": "Do not remember relay state",
					"value": 0
				},
				{
					"label": "Remember relay state",
					"value": 1
				}
			]
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "Timer plug OFF after time period",
```suggestion
			"label": "Timed auto-off",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "Delay time after the plug is switched off (in minutes)",
```suggestion
			"label": "Timed auto-off period",
			"description": "Delay time after which the plug is automatically switched off",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"unit": "Minutes",
```suggestion
			"unit": "minutes",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			"description": "Enable/Disable top button function",
```suggestion
			"label": "Top button function",
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01z.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
> +			"description": "Plug state after power-on",
see previous file

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
>  					"value": 1
see previous file

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
> +			"description": "Enable/Disable top button function",
see previous file

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
>  				}
see previous file

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
>  				}
same for all the other parameters that exist in both files

2021-03-12 16:15 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-wr01ze.json
> +			"unit": "cA",
What kind of unit is this? I guess `"0.01 A"` which we prefer because it is obvious.

2021-03-15 02:14 UTC, blhoward2 commented
@Masterz69 Earlier today we merged detailed documentation on device files, including a style guide and detailed guidance on templating. Could you please take a look at those, make any changes necessary to conform, and then let us know when you're ready for us to take a look line-by-line?

https://zwave-js.github.io/node-zwave-js/#/

2021-03-16 16:51 UTC, AlCalzone requested changes
What @blhoward2 said :)

2021-03-16 17:59 UTC, Masterz69 commented
Both files styling adjustment - label, descriptions & units.

2021-03-16 18:16 UTC, Masterz69 commented
@zwave-js-bot fix lint

2021-03-16 20:40 UTC, AlCalzone approved these changes
Thanks!

2021-03-16 20:46 UTC, merged