feat: add config
AlCalzone/node-zwave-js pull request #2040
Opened 2021-03-11 02:54 UTC by blhoward2

Fixes @Juggler00's issue in #1713. Yale released some locks with an incorrect manufacturerId.

2021-03-11 07:06 UTC, AlCalzone requested changes

2021-03-11 07:06 UTC, AlCalzone commented on packages/config/config/devices/0x0109/yrd210.json
> +	"manufacturerId": "0x0109",
Could use a comment here that mentions the incorrect manufacturer ID

2021-03-11 07:06 UTC, AlCalzone commented on packages/config/config/devices/0x0109/yrd210.json
> +			"productId": "0x0000"
Do they all use the same product ID?

2021-03-12 04:31 UTC, blhoward2 commented on packages/config/config/devices/0x0109/yrd210.json
> +			"productId": "0x0000"
As far as I can tell, yes.

2021-03-12 07:53 UTC, AlCalzone approved these changes

2021-03-12 13:05 UTC, merged