fix(config): split lzw31-sn param 16 normalize param names
AlCalzone/node-zwave-js pull request #2069
Opened 2021-03-14 13:53 UTC by mattsch

2021-03-14 14:04 UTC, mattsch commented
I was also considering adding the duration options like Inovelli has for their [Hubitat](https://github.com/InovelliUSA/Hubitat/blob/master/Drivers/inovelli-switch-red-series-lzw30-sn.src/inovelli-switch-red-series-lzw30-sn.groovy#207) and [SmartThings](https://github.com/InovelliUSA/SmartThingsInovelli/blob/935149ee19ab807378a9906cf70a778e92e9dbe7/devicetypes/inovelliusa/inovelli-dimmer-red-series-lzw31-sn.src/inovelli-dimmer-red-series-lzw31-sn.groovy#L299). Any objections @AlCalzone?

2021-03-14 17:29 UTC, AlCalzone commented
> I was also considering adding the duration options like Inovelli has for their [Hubitat](https://github.com/InovelliUSA/Hubitat/blob/master/Drivers/inovelli-switch-red-series-lzw30-sn.src/inovelli-switch-red-series-lzw30-sn.groovy?rgh-link-date=2021-03-14T14%3A04%3A16Z#207) and [SmartThings](https://github.com/InovelliUSA/SmartThingsInovelli/blob/935149ee19ab807378a9906cf70a778e92e9dbe7/devicetypes/inovelliusa/inovelli-dimmer-red-series-lzw31-sn.src/inovelli-dimmer-red-series-lzw31-sn.groovy#L299). Any objections @AlCalzone?

Not as single options please. These can stay as manual entry with a corresponding description.

2021-03-14 17:36 UTC, AlCalzone requested changes
A few things... and since you touched these files (sorry 😉), I think we should consolidate the different LZW31 files using conditional parameters now.

See https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings for details. Might also be worth to check out our brand-new [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide)

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Fan LED Strip Effect Type. 0 = Off, 1 = Solid, 2 = Slow Blink, 3 = Fast Blink, 4 = Chase, 5 = Pulse Default: 0",
That description does not add value over what is defined below. Please remove.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
>  			"description": "Fan LED Strip Duration. 1 to 60 = seconds, 61 to 120 minutes, 121 - 254 = hours, 255 = Indefinitely Default: 0",
```suggestion
			"description": "Fan LED Strip Duration. 1 to 60 = seconds, 61 to 120 minutes, 121 - 254 = hours, 255 = Indefinitely",
```
There is some discrepancy here. The old description said default is 0, you define 255 below. And if 255 is correct, 0 has no meaning.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Fan LED Strip Brightness 0 to 10. 0 = dim, 10 = bright Default: 3",
Description seems unnecessary. Remove please.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Fan LED Strip Brightness 0 to 10. 0 = dim, 10 = bright Default: 3",
Please also check the other parameters that are similar.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
>  			"description": "Fan LED Strip Duration. 1 to 60 = seconds, 61 to 120 minutes, 121 - 254 = hours, 255 = Indefinitely Default: 0",
Please also check the other parameters that are similar.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Fan LED Strip Effect Type. 0 = Off, 1 = Solid, 2 = Slow Blink, 3 = Fast Blink, 4 = Chase, 5 = Pulse Default: 0",
Please also check the other parameters that are similar.

2021-03-14 17:36 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
>  			"description": "Light LED Strip Effect Color. Color - 0 - 255. Hue color wheel. value/255 * 360 = Hue color wheel value Range: 0-255 Default: 0",
While we're cleaning up, this description should be simplified - it is a bit redundant in itself. Please no range/default in descriptions.

Please also check the other parameters that are similar.

2021-03-15 00:53 UTC, mattsch commented
@zwave-js-bot fix lint

2021-03-15 00:58 UTC, mattsch commented
@AlCalzone So it should all be consistent. May be wrong, but at least it's all consistently wrong. 😄

2021-03-15 07:56 UTC, AlCalzone requested changes
A few more things

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw30-sn.json
> +			"description": "Controls the 700ms button delay. Note, if you disable the delay, it will also disable multi-tap scenes.",
```suggestion
			"description": "Enabling this disables the 700ms button delay and multi-tap scenes.",
```
Seems a bit less confusing to me.

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw30-sn.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw31-sn.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw31-sn.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw31-sn.json
> +			"description": "Controls the 700ms button delay. Note, if you disable the delay, it will also disable multi-tap scenes.",
```suggestion
			"description": "Enabling this disables the 700ms button delay and multi-tap scenes.",
```
Seems a bit less confusing to me.

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
>  			"label": "Light Ramp Rate",
Please make this consistent with param 12/13

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"label": "Light Ramp Rate From Switch",
Please make this consistent with param 12/13

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "1 to 60 = seconds, 61 to 120 = minutes, 121 - 254 = hours, 255 = indefinitely",
```suggestion
			"description": "1 to 60 = seconds, 61 to 120 = minutes (minus 60), 121 - 254 = hours (minus 120), 255 = indefinitely",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "1 to 60 = seconds, 61 to 120 = minutes, 121 - 254 = hours, 255 = indefinitely",
See 24[0xff0000]

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Enables for these buttons.",
```suggestion
```

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw36.json
> +			"description": "Controls the 700ms button delay. Note, if you disable the delay, it will also disable multi-tap scenes.",
See other variants of this parameter where I proposed a diffent description.

2021-03-15 07:56 UTC, AlCalzone commented on packages/config/config/devices/0x031e/lzw30-sn.json
> +			"description": "Uses a scaled hue value (realHue/360 * 255).",
```suggestion
			"description": "Uses a scaled hue value (realHue / 360 * 255).",
```

2021-03-15 23:57 UTC, mattsch commented
@AlCalzone I believe this should be ready to go.

2021-03-16 08:00 UTC, AlCalzone approved these changes

2021-03-16 08:01 UTC, merged