fix: add ConfigurationMetadata as return type for node.getValueMetadata
AlCalzone/node-zwave-js pull request #2193
Opened 2021-03-29 23:27 UTC by raman325

`node.getValueMetadata` and `getCCValueMetadata` can return `ConfigurationMetadata` in addition to `ValueMetadata`

2021-03-30 16:16 UTC, AlCalzone requested changes

2021-03-30 16:47 UTC, raman325 commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
should we move `ConfigValue` and `ValueFormat` as well?

2021-03-30 20:49 UTC, raman325 commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
What would you want the `type` to be?

2021-03-30 21:05 UTC, raman325 commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
Actually, thinking about it some more, I'm not sure that changing the type is a good idea. For every other type it describes the value type and can be used to figure out how to parse it. If we do want a unique type, I think we would want to name it something that makes it clear what data type the value is.

2021-03-31 14:44 UTC, raman325 commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
Well without this change, I would expect the type to be either `number`, `number[]`, or `boolean` in those cases no? So maybe we should just append `config_` as a prefix to those for config values?

2021-03-31 14:46 UTC, raman325 commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
or camel case so `configNumber` etc.

2021-03-31 21:24 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +	): ValueMetadata | ConfigurationMetadata {
Let's keep it like it is for now - if it seems necessary, we can add a type to distinguish.

2021-03-31 21:25 UTC, AlCalzone approved these changes

2021-04-05 13:49 UTC, merged