feat: new node events for interviewing and node not ready
AlCalzone/node-zwave-js pull request #2233
Opened 2021-04-02 05:22 UTC by raman325

As discussed in Discord, I added three new events:
- `interview started`
- `interview stage completed`
- `not ready`

This will allow us to update the ready status in `zwave-js-server-python` as needed, and also will allow us to display information to the user about the last completed stage of interview during a re-interview or during startup

2021-04-02 09:49 UTC, AlCalzone requested changes
I don't like the `"not ready"` event. This only happens when a node is manually re-interviewed. If you need that event I'd prefer you add it in `zwave-js-server` and raise it whenever you call `refreshInfo` on a node. This could be mentioned in the docs for `refreshInfo` though.

2021-04-02 19:58 UTC, raman325 commented
Do you have any guidance on the expected behavior of a node when it is not ready? Should we assume that the node needs to be left alone until the interview finishes, e.g. disable all interaction with the node?

2021-04-04 23:16 UTC, AlCalzone commented
> Should we assume that the node needs to be left alone until the interview finishes, e.g. disable all interaction with the node?

Yes. Like during the initial interview, you should not interact with a node that is not ready. So after calling `refreshInfo`, you need to wait for the `ready` event.

2021-04-04 23:16 UTC, AlCalzone approved these changes

2021-04-05 13:48 UTC, merged