Update zw056.json
AlCalzone/node-zwave-js pull request #2236
Opened 2021-04-03 17:41 UTC by jamesdawson3

To allow playing ringtones on demand.  Allowable range for parameter 6 should be 0-100, not a set of options:

http://manuals-backend.z-wave.info/make.php?lang=en&sku=ZW056-C&cert=ZC10-15110019

2021-04-03 17:47 UTC, jamesdawson3 commented
@zwave-js-bot fix lint

2021-04-05 14:05 UTC, AlCalzone requested changes
The referenced $import is defined as follows:
```
	"base_0-100_nounit": {
		"valueSize": 1,
		"minValue": 0,
		"maxValue": 100,
		"defaultValue": 1,
		"unsigned": true,
		"readOnly": false,
		"writeOnly": false,
		"allowManualEntry": true
	},
```
so all you'd have to change is `defaultValue: 0` if that is correct. Because of `allowManualEntry: true`, the option is just a hint/predefined value.

2021-04-05 14:41 UTC, jamesdawson3 commented
Thanks for pointing me at the $import, that's helpful to understand.  Also largely makes my PR unnecessary.  Perhaps my issue is a Home Assistant implementation problem.  

The following is from my zwave_js_dump - which correctly matches the config file (with the $import):
`              {
                "endpoint": 0,
                "commandClass": 112,
                "commandClassName": "Configuration",
                "property": 6,
                "propertyName": "Play Ringtone",
                "ccVersion": 1,
                "metadata": {
                  "type": "number",
                  "readable": true,
                  "writeable": true,
                  "label": "Play Ringtone",
                  "default": 1,
                  "min": 0,
                  "max": 100,
                  "states": {
                    "0": "Stop playing"
                  },
                  "valueSize": 1,
                  "format": 1,
                  "allowManualEntry": true,
                  "isFromConfig": true
                }
              },`

However, when I try to set the parameter in HA, it fails if I set the value to anything other than 0:

`Failed to call service zwave_js/set_config_parameter. Must provide a value that represents a valid state key or label from {"0": "Stop playing"}`

Seems like HA is inappropriately requiring one of the defined states, if states are defined.

2021-04-05 14:45 UTC, AlCalzone commented
> Seems like HA is inappropriately requiring one of the defined states, if states are defined.

Looks like it. I think that's changed in the `.4` release, but I'm not 100% sure.

2021-04-05 15:01 UTC, closed without merging