fix(config): correct Linear wd500z
AlCalzone/node-zwave-js pull request #2391
Opened 2021-04-17 19:22 UTC by cdnninja

Corrected to spec for the Linear wd500z.  Could you please confirm zwave js will identify this as different than the nortek?  Only difference is a z-wave alliance ID.  Device IDs are identical.  Only updating as it already existing in zwave JS. https://github.com/zwave-js/node-zwave-js/blob/541ddb486173882b99f908cd437982367e15379a/packages/config/config/devices/0x014f/wd500z-1.json

2021-04-18 15:06 UTC, AlCalzone commented
> Could you please confirm zwave js will identify this as different than the nortek?

Yes, the manufacturerId is different - so it is a different device as far as zwave-js is concerned.

2021-04-18 15:07 UTC, AlCalzone requested changes
I know you didn't touch that, but the device descriptions reads
`"description": "Linear -1",`
Is that correct? Seems weird.

2021-04-18 17:44 UTC, cdnninja commented
Hard to get details on it.  From what I can tell they are actually called WD500Z-1 so I assume that is the reference.  I will update the details. https://products.z-wavealliance.org/products/1032?selectedFrequencyId=2

2021-04-18 22:48 UTC, blhoward2 commented
This is a dimmer switch, right? I've changed the description as we try not to repeat the model number. Also, this is marketed under the Linear name, right? If so that should be the brand indicated.

2021-04-18 22:52 UTC, blhoward2 approved these changes

2021-04-19 17:32 UTC, AlCalzone approved these changes

2021-04-19 17:32 UTC, merged