fixe(conf) : change scenes sent config and on/off mode - fibaro walli dimmer
AlCalzone/node-zwave-js pull request #2425
Opened 2021-04-22 10:37 UTC by Micka41

fixe : #2424

2021-04-22 12:31 UTC, Micka41 commented
@zwave-js-assistant update

2021-04-22 12:35 UTC, AlCalzone requested changes
Thanks! Unfortunately this device file seems to come from an earlier automated import from other projects and contains some more errors and/or needs cleaning up.

Since you touched it, we should make sure it is up to our standards. Please read the Style Guide and make the necessary corrections where necessary.

If you have any questions, @blhoward2 and I will gladly assist you.

2021-04-22 12:35 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgwdeu.json
> +			"description": "determines which actions result in sending scene IDs (0 - no scenes; 1 - Key pressed once; 2 - Key pressed twice; 4 - Key pressed 3 times; 8 - Key held down and released)",
This should be modeled as [partial parameters](https://zwave-js.github.io/node-zwave-js/#/config-files/file-format?id=partial-parameters)

2021-04-22 12:35 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgwdeu.json
> +			"description": "determines which actions result in sending scene IDs (0 - no scenes; 1 - Key pressed once; 2 - Key pressed twice; 4 - Key pressed 3 times; 8 - Key held down and released)",
dito

2021-05-06 18:31 UTC, AlCalzone commented
@Micka41 are you still interested in getting this merged?

2021-05-07 06:24 UTC, Micka41 commented
> @Micka41 are you still interested in getting this merged?

Yes, maybe today

2021-09-08 09:31 UTC, closed without merging