fix(config): corrected partial paramaters in Philio Technology Corp PST02-C
AlCalzone/node-zwave-js pull request #2617
Opened 2021-05-15 01:36 UTC by cdnninja

2021-05-15 01:44 UTC, cdnninja commented
@zwave-js-bot fix lint

2021-05-15 11:34 UTC, AlCalzone requested changes
Some of the descriptions are suboptimal - either broken english or unnecessary because they just repeat the label in more words. Plus two small errors

2021-05-15 11:34 UTC, AlCalzone commented on packages/config/config/devices/0x013c/pst02c.json
> +			]
One of these is not correct :D

2021-05-15 11:34 UTC, AlCalzone commented on packages/config/config/devices/0x013c/pst02c.json
> +			"defaultValue": 255
```suggestion
			"defaultValue": 255,
			"unsigned": true
```

2021-05-18 02:26 UTC, cdnninja commented
I have some more labels to edit however interested on thoughts on this.  The manual isn't clear if these are actually double negatives or not.  An example: `Disable send out BASIC OFF after door closed. (1:Disable, 0:Enable)` So do you enable it to disable send basic off?   I assume this is defaulted to 1 due to the order as well.  I have a few assumptions I have to make when reading this manual.

2021-05-18 06:33 UTC, AlCalzone commented
I think this configures whether a Basic Set is sent or not, with the default being "No".
I don't think these are double negatives, just bad labels.

2021-05-20 10:44 UTC, AlCalzone requested changes

2021-05-20 10:46 UTC, AlCalzone approved these changes
Ok with my changes

2021-05-20 12:34 UTC, merged