fix(config): logic group config files
AlCalzone/node-zwave-js pull request #2638
Opened 2021-05-18 20:15 UTC by Roagert

zso7300 and zdi5200 fix
fixes zwave-js#2623

2021-05-18 20:53 UTC, AlCalzone requested changes

2021-05-18 20:53 UTC, AlCalzone commented on packages/config/config/devices/0x0234/templates/logic_group_template.json
> +	},
I don't think this is used anywhere.

2021-05-18 20:53 UTC, AlCalzone commented on packages/config/config/devices/0x0234/zso7300.json
> +		},
The import `base_enable_disable` doesn't make sense here. It is a toggle for `Enable (1)` / `Disable (0)`.
I must have overlooked that last time.

2021-05-23 21:15 UTC, AlCalzone commented
ping @Roagert I can't merge like this.

2021-05-23 21:16 UTC, Roagert commented
> ping @Roagert I can't merge like this.

What you need me to do?

2021-05-23 21:38 UTC, AlCalzone commented
See review comment: https://github.com/zwave-js/node-zwave-js/pull/2638/files/8d8a4384bf5633e5423338bbe24d9db464daee52#r634740232

2021-05-24 16:31 UTC, AlCalzone approved these changes

2021-05-24 16:32 UTC, merged

2021-05-24 16:32 UTC, AlCalzone commented
Thanks!

2021-05-24 17:09 UTC, Roagert commented
> Thanks!

You're welcome :)