feat(config): added support for sunricher ZV2835RAC-NF
AlCalzone/node-zwave-js pull request #2657
Opened 2021-05-21 00:43 UTC by cdnninja

closes #2570.

2021-05-21 01:02 UTC, cdnninja commented
@zwave-js-bot fix lint

2021-05-21 07:03 UTC, AlCalzone requested changes
Please give this a second pass - there are several labels and descriptions that don't align with the style guide. I've highlighted some of them.

2021-05-21 07:03 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			]
This comes up often enough that we should make two master templates for it. One with "previous state", one without.

IMO, this is the preferred definition (short and clear):
```suggestion
			"label": "State After Power Failure",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 2,
			"defaultValue": 2,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Off",
					"value": 0
				},
				{
					"label": "On",
					"value": 1
				},
				{
					"label": "Previous State",
					"value": 2
				}
			]
```

2021-05-21 07:03 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			]
```suggestion
			"label": "Send Basic Report",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 1,
			"defaultValue": 1,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-05-21 07:03 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +					"label": "Enable to detect only after first re-power",
```suggestion
					"label": "Only after first re-power",
```

2021-05-21 07:03 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"description": "Enable/disable to detect load",
```suggestion
```

2021-05-21 21:52 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			]
Once #2665 is merged, the preferred one would be
```suggestion
"$import": "../templates/master_template.json#state_after_power_failure_off_on_prev"
```

2021-05-23 21:44 UTC, AlCalzone requested changes

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Default fade time",
```suggestion
			"label": "Default Fade Time",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			]
I guess you're supposed to enter the values here, so this definition doesn't work. You can leave the Instantly and Factory default options. The rest with changing unit can be done as a description:
```
Values 1-127 = seconds; 128-254 = minutes (minus 127)
```
but you'll need `"allowManualEntry": true,`

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Minimum brightness value",
```suggestion
			"label": "Minimum Brightness Value",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Maximum brightness value",
```suggestion
			"label": "Maximum Brightness Value",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"defaultValue": 100
In Z-Wave the brightness (level) goes from 0 to 99, so I think this needs to be changed:
```suggestion
			"minValue": 0,
			"maxValue": 99,
			"defaultValue": 99
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "MOSFET driving type",
```suggestion
			"label": "MOSFET Driving Type",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Step of knob",
```suggestion
			"label": "Step of Knob",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +		},
I don't understand this param

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Detect load",
```suggestion
			"label": "Detect Load",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Wiring type",
```suggestion
			"label": "Wiring Type",
```
Any explanation what these types mean?

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Load type",
```suggestion
			"label": "Load Type",
```
Any explanation what these types mean?

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Over current protection",
```suggestion
			"label": "Over Current Protection",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Power automatic report absolute threshold",
```suggestion
			"label": "Automatic Power Report: Absolute Threshold",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Power automatic report threshold,",
```suggestion
			"label": "Automatic Power Report: Relative Threshold",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Power metering time cycle",
```suggestion
			"label": "Power Metering Time Cycle",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Energy metering time cycle",
```suggestion
			"label": "Energy Metering Time Cycle",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Voltage metering time cycle",
```suggestion
			"label": "Voltage Metering Time Cycle",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Current metering time cycle",
```suggestion
			"label": "CurrentMetering Time Cycle",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Dimming curve",
```suggestion
			"label": "Dimming Curve",
```

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"options": [
This should have `allowManualEntry: false`

2021-05-23 21:44 UTC, AlCalzone commented on packages/config/config/devices/0x0330/zv2835rac-nf.json
> +			"label": "Starting brightness",
```suggestion
			"label": "Starting Brightness",
```

2021-05-25 00:33 UTC, cdnninja commented
@AlCalzone  is this lint error a mistake in logic on the check?

2021-05-25 21:33 UTC, AlCalzone commented
No, its a somewhat recent change to the lint rules. `allowManualEntry` defaults to `true` for writable parameters and can now only be set to `false` or left out.

2021-05-25 21:38 UTC, AlCalzone approved these changes

2021-05-25 21:46 UTC, merged