fix(config): Add Neo Coolcam Motion Sensor 2
AlCalzone/node-zwave-js pull request #2821
Opened 2021-06-08 22:59 UTC by bwosborne2

Also removed device from motion_sensor.

2021-06-09 21:01 UTC, AlCalzone commented
This is supposed to fix #2738, correct?

Side note: The original file does not comply with the style guide, we should clean that up after this PR is merged.

2021-06-09 21:16 UTC, AlCalzone requested changes

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"unit": "LUX",
```suggestion
			"unit": "lux",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"label": "Sensitivity Level Setting",
```suggestion
			"label": "Sensitivity Level",
```
Also, the description is repetitive and should explain the values (e.g. 8 = low, 255 = high)

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"unit": "Seconds",
```suggestion
			"unit": "seconds",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Determines how long the associated devices should stay ON status",
```suggestion
			"label": "On/Off Duration",
			"description": "Determines how long the associated devices should stay on",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"label": "Enable/Disable PIR Function",
```suggestion
			"label": "PIR Detector",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 255
				}
			]
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Set a lux level value which determines when the light sensor is activated.",
```suggestion
			"label": "Light Sensor Brightness Threshold",
			"description": "The light sensor is active when the brightness is above this level",
```
Not sure about the description - is that correct or the other way round?

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"unit": "LUX",
```suggestion
			"unit": "lux",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"unit": "Seconds",
```suggestion
			"unit": "seconds",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"unit": "Seconds",
```suggestion
			"unit": "seconds",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Adjust the interval of PIR being re-triggered",
```suggestion
			"label": "PIR Re-trigger Interval",
			"description": "Must be less than the On/Off Duration",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "The Interval after which the Light Sensor Measure is polled.",
tbh I read the manual and still don't understand this. I think there's a better description

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "0 = Off, 1 =On",
```suggestion
			"label": "Lux Level Function",
			"description": "When enabled, send Basic Set if brighness falls below threshold.",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Differential between current & previous report",
```suggestion
			"label": "Temperature Differential Report Threshold",
			"unit": "0.1 °C",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Defines whether the LED blinking is on / off",
```suggestion
			"label": "LED: Blink on Motion",
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +				}
```suggestion
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
```

2021-06-09 21:16 UTC, AlCalzone commented on packages/config/config/devices/0x0258/motion_sensor_2.json
> +			"description": "Define the calibrated scale for ambient light intensity",
```suggestion
			"label": "Ambient Light Intensity Calibration",
```
I don't understand the manual here 🤷🏻‍♂️

2021-06-09 21:30 UTC, bwosborne2 commented
Sorry, I based the new file off the old one, assuming it had passed your checks.

Also, I could not find out how to fix the semantic title / commit message check. Where is that documented?

2021-06-09 21:39 UTC, AlCalzone commented
> assuming it had passed your checks

Many of our files were automatically imported and functionally validated quite some time ago. The style guide is pretty new and requires manual intervention. We apply it as we go, so many files aren't up to date yet.

> Also, I could not find out how to fix the semantic title / commit message check

I did that for you. The message must be in the format
```
changetype(config): lowercase Rest of the SENTENCE
                    ^^^^^^^^^
```

2021-06-10 20:56 UTC, AlCalzone commented
I think you overlooked those - did it for you:
![grafik](https://user-images.githubusercontent.com/17641229/121595952-21938b00-ca3f-11eb-8dfe-f2065485be24.png)

2021-06-10 20:57 UTC, AlCalzone approved these changes

2021-06-10 21:30 UTC, bwosborne2 commented
Thanks. I thought I got them all...

2021-06-11 22:24 UTC, merged