feat(config): add config for Minoston MP21ZD
AlCalzone/node-zwave-js pull request #2905
Opened 2021-06-24 01:13 UTC by 3van

Parameter definitions based off of the manual linked in metadata, and tested locally with the one that just arrived at my house.

2021-06-24 07:37 UTC, AlCalzone requested changes
Thanks - a few minor edits please

2021-06-24 07:37 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21zd.json
> +		},
We now have [templates](https://github.com/zwave-js/node-zwave-js/blob/6c4d9d026a44d656e3b4d1011d7b1215cfa29ce3/packages/config/config/devices/templates/master_template.json#L256-L405) for the variants of this config option. Please choose the matching one and use it.

2021-06-24 07:37 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21zd.json
> +			"unit": "%",
```suggestion
```
Nitpicking,  but brightness in Z-Wave is not in %. See the note above https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide?id=readwrite-only

2021-06-24 07:37 UTC, AlCalzone commented on packages/config/config/devices/0x0312/mp21zd.json
> +			"label": "Temperature Delta Threshold For Report",
```suggestion
			"label": "Temperature Report Change Threshold",
```

2021-07-26 21:31 UTC, AlCalzone commented
Hey @3van are you planning on finishing this PR?

2021-09-05 11:02 UTC, AlCalzone approved these changes

2021-09-05 11:07 UTC, merged

2021-12-09 15:48 UTC, geeregman commented
First, thank you for all your work.
I just want to comment; I found that the MP21ZD configuration values are 'inverted':
I needed the switch to be in the on state after return from a power outage.
I had to set the 'state after power failure' to OFF in order for the switch to be ON after power is returned, which is backwards from what I want. Also, the LED indicator setting is backwards, that is, setting LED on with load OFF, in actuality the load is ON when the LED is ON.
I am using homeassistant and ZWavejs2mqtt control panel.  Everything works as it should, just that the configuration settings seem to be inverted................

2021-12-09 21:14 UTC, AlCalzone commented
@geeregman any chance you have a manual to confirm this against?

2021-12-10 12:58 UTC, geeregman commented
Attached is the manual I have from Minoston.

In the 'Restores after power failure' section.
Value 1 is always OFF, and Value 2 is always ON.

In the 'LED Indicator section' the values in the guide are incorrect.

I have been in contact with Minoston regarding the incorrect LED indicator section.
attached is a copy an email from them.


thanks,
Greg

________________________________
From: AlCalzone ***@***.***>
Sent: Thursday, December 9, 2021 16:14
To: zwave-js/node-zwave-js ***@***.***>
Cc: geeregman ***@***.***>; Mention ***@***.***>
Subject: Re: [zwave-js/node-zwave-js] feat(config): add config for Minoston MP21ZD (#2905)


@geeregman<https://github.com/geeregman> any chance you have a manual to confirm this against?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/zwave-js/node-zwave-js/pull/2905#issuecomment-990260646>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACOSG6TRCPHUGWXR7WWRFX3UQEL37ANCNFSM47G36S7Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-12-10 13:03 UTC, AlCalzone commented
I don't see anything attached. Note that replying to issues via email does not preserve the attachments. You'll have to do that via the web.

2021-12-10 13:10 UTC, geeregman commented
Here are the files (I think)
[ZwavesmartplugMinostonMP21ZP.pdf](https://github.com/zwave-js/node-zwave-js/files/7692910/ZwavesmartplugMinostonMP21ZP.pdf)
[MinostonEmailReply.pdf](https://github.com/zwave-js/node-zwave-js/files/7692924/MinostonEmailReply.pdf)

2021-12-10 19:19 UTC, AlCalzone commented
Thanks, PR #3878 opened