Add missing paramInformation and metadata
AlCalzone/node-zwave-js pull request #2951
Opened 2021-07-02 11:44 UTC by crxporter

Copied missing data from this same device with different mfg/product IDs:

https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0039/39351_jasco_zw3010.json

2021-07-02 12:14 UTC, AlCalzone commented
@blhoward2 any concerns?

2021-07-15 03:15 UTC, blhoward2 requested changes
Minor nits.

2021-07-15 03:15 UTC, blhoward2 commented on packages/config/config/devices/0x0063/46203.json
> +			"description": "LED status when device on or off.",
Unnecessary description. Usually we say "LED Indicator."

2021-07-15 03:15 UTC, blhoward2 commented on packages/config/config/devices/0x0063/46203.json
> +			"description": "Switch orientation.",
Unnecessary description.

2021-07-15 16:07 UTC, crxporter commented
Give me a thumbs up on this comment if you'd like me to make those changes on all of these devices. It's at least 3, I can probably check some others I know are similar though. 

Thumbs down if you just want me to fix the single file in this PR.

2021-07-16 03:24 UTC, blhoward2 commented
You can, but this folder is on my list to template and go through anyway so it isn't necessary unless you really want to do so.

2021-07-16 11:40 UTC, crxporter commented
Alright - for now I'll just stick with this file. I've made the requested edits.

I don't have any reason to get in the way of your process.

Thanks!

2021-07-23 22:11 UTC, crxporter commented
Bump. I'm at a point I need these config options, can it be merged?

2021-07-24 01:51 UTC, blhoward2 approved these changes
Sorry, been busy. LGTM

2021-07-26 21:23 UTC, merged