fix(config): add metadata to Nortek devices
AlCalzone/node-zwave-js pull request #3022
Opened 2021-07-15 00:47 UTC by disforw

2021-07-15 04:59 UTC, disforw commented
@zwave-js-bot fix lint

2021-07-19 11:41 UTC, AlCalzone commented
@blhoward2 I think this could use your review

2021-07-28 02:52 UTC, blhoward2 requested changes

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/lb60z-1.json
> +			"description": "Bulb brightness when turned on",
I think this description can be the label. No need for both.

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/lb60z-1.json
> +					"label": "Memory Brightness",
Change to "Prior brightness level"

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/lb60z-1.json
> +			"label": "Dim/Bright Step Level",
Just make this "Dim Step Levels"

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/lb60z-1.json
> +			"label": "Dim/Bright Speed",
Make this "Dim Speed"

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/wo15z.json
> +			"label": "Status LED",
Change to "LED Indicator"

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/wo15z.json
>  			"description": "LED mode for attached load",
Remove description.

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/ws15z-1.json
>  			"label": "Night Light",
Change to "LED Indicator"

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/ws15z-1.json
> +			"description": "By default, the LED will turn OFF when the load attached is turned ON.",
Remove description.

2021-07-28 02:52 UTC, blhoward2 commented on packages/config/config/devices/0x014f/ws15z-1.json
> +					"label": "OFF when load is on",
Don't capitlize the entirety of ON and OFF. Just "On" and "Off". Please carry throughout all files.

2021-07-28 13:50 UTC, disforw commented on packages/config/config/devices/0x014f/lb60z-1.json
> +					"label": "Memory Brightness",
Done

2021-08-02 21:16 UTC, AlCalzone commented
@disforw just FYI, the re-review might take a few days

2021-08-20 03:09 UTC, blhoward2 submitted a review, later dismissed
Approved with minor changes committed

2021-08-22 09:10 UTC, AlCalzone approved these changes
Not sure how I dismissed the other review 🤷🏻‍♂️

2021-08-22 09:10 UTC, merged