fix(config): change scenes sent config - fibaro walli roller
AlCalzone/node-zwave-js pull request #3303
Opened 2021-09-08 12:45 UTC by Micka41

2021-09-08 14:25 UTC, Micka41 commented
Hello, 
What's wrong this time?

2021-09-08 14:33 UTC, AlCalzone commented
To be fair, I have no clue. Something crashes during unit tests.

2021-09-08 14:41 UTC, AlCalzone commented
Bug in Node.js 16.9:
https://github.com/nodejs/node/issues/40030

2021-09-08 15:56 UTC, Micka41 commented
Ok thanks.
How to restart it ?

2021-09-08 21:07 UTC, AlCalzone commented
I'll do it once I've changed the testing.

2021-09-08 21:20 UTC, AlCalzone commented
@Mergifyio update

2021-09-11 20:27 UTC, blhoward2 requested changes

2021-09-11 20:27 UTC, blhoward2 commented on packages/config/config/devices/0x010f/fgwreu-111.json
>  		"31": {
I've made some changes for you to get going, but please cleanup the remainder of the file according to our style guide. https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide

I know that these are pre-existing errors, but we appreciate your help in cleaning the file up.

2021-09-11 20:27 UTC, blhoward2 commented on packages/config/config/devices/0x010f/fgwreu-111.json
> +			"maxValue": 4,
If there are only four options, can we define these as options so they use a drop-down? Do you know what they are?

2021-10-12 13:44 UTC, AlCalzone commented
#3100 was just merged, so I've gone ahead and updated your file to match the new config format. As you'll see, paramInformation is now an array of objects.

I did not touch anything else, so please update the file according to the review comments

2021-11-19 08:36 UTC, AlCalzone commented
@Micka41 are you planning to finish this?

2022-02-02 16:45 UTC, closed without merging