Update Philio PSM02 Configuration
AlCalzone/node-zwave-js pull request #3373
Opened 2021-09-20 06:01 UTC by orandasoft

- Add lifeline association group
- Update configuration parameter 5 and 6 to use partial parameters
- Add configuration parameter 7 as partial parameters
- Some minor cosmetic changes

2021-09-20 07:33 UTC, AlCalzone requested changes

2021-09-20 07:33 UTC, AlCalzone commented on packages/config/config/devices/0x013c/psm02.json
> +	"supportsZWavePlus": false,
```suggestion
```
We don't use that anymore

2021-09-20 07:33 UTC, AlCalzone commented on packages/config/config/devices/0x013c/psm02.json
> +			"label": "Send motion OFF report. ",
```suggestion
			"label": "Send Motion Off Report",
```
Please check that all other labels are *Title Case* without punctuation.

2021-09-20 07:33 UTC, AlCalzone commented on packages/config/config/devices/0x013c/psm02.json
>  	}
```suggestion
	},
```

2021-09-20 07:39 UTC, orandasoft commented on packages/config/config/devices/0x013c/psm02.json
> +	"supportsZWavePlus": false,
Found that in the PST02A configuration.

2021-09-20 07:47 UTC, orandasoft commented
Corrected case in one additional line.

2021-09-20 08:50 UTC, orandasoft commented
How do I run prettier?

2021-09-20 08:55 UTC, AlCalzone commented
If you're using VSCode and have installed the recommended extensions and all dependencies, you just need to save the file. Otherwise:
@zwave-js-bot fix lint

2021-09-20 09:57 UTC, orandasoft commented
This newbie will use @zwave-js-bot fix lint until graduating to VSCode.

2021-09-20 23:17 UTC, orandasoft commented
Is there anything left to do?

2021-09-21 11:29 UTC, AlCalzone approved these changes

2021-09-21 11:30 UTC, AlCalzone commented
Just noticed a little thing you didn't touch. Changes look good otherwise.

2021-09-21 11:33 UTC, merged