Param #42: Fix units and default value and add to Label info
AlCalzone/node-zwave-js pull request #3689
Opened 2021-11-09 18:10 UTC by fojie

PR description here
Fix error in param #42 for ZMNHTD1. Adjusted according to Qubino User manual.

2021-11-10 07:29 UTC, AlCalzone requested changes

2021-11-10 07:29 UTC, AlCalzone commented on packages/config/config/devices/0x0159/zmnhtd.json
> +			"label": "Power reporting (Watts) by time interval (0-59 = reporting disabled)",
```suggestion
			"label": "Power (W) Reporting Interval",
			"description": "Allowable range: 60-32535",
```
and under the default value add an option:
```jsonc
			"options": [
				{
					"label": "Disable",
					"value": 0
				}
			]
```

2021-11-19 08:39 UTC, AlCalzone commented
@fojie are you planning to finish this?

2021-11-19 20:41 UTC, fojie commented
Hi,

Sorry for this. This is my first ever PR, and to be honest I don't have time to learn how to do the steps remaining. I thought the first step I did was enough, but obviously the PR could be improved and I don't know how to go further.

So, I suggest that I stick to just finding bugs, and let others – that handles PRs in a proper way –  do the PRs.

Is this OK? I'll gladly hand it over to you. Is that's possible I think it takes less time for you, than to try to tech my how to do it.

	Best Regards
	Folke



> 2021-11-19	 kl. 09:39 skrev AlCalzone ***@***.***>:
> 
> 
> @fojie <https://github.com/fojie> are you planning to finish this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/zwave-js/node-zwave-js/pull/3689#issuecomment-973868519>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AC37DHI5IPYATILVMUF2G6TUMYELJANCNFSM5HV6CDOA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-11-19 22:12 UTC, AlCalzone commented
Its not that hard, I described the two necessary changes above - you'll just need to edit the file again and do the changes. Its okay though if you don't feel confident here.

2022-02-02 16:45 UTC, closed without merging