fix(config): Add Spectrum Brands 893 deadbolt
AlCalzone/node-zwave-js pull request #3715
Opened 2021-11-15 16:23 UTC by Botched1

Add Spectrum Brands 893 device configuration. This is exactly the same as the Spectrum Brands 892 already in the database, but this version is zwave 700.

Took the 892 file and changed productId, zwaveAllianceId, and link to the manual.

2021-11-15 16:25 UTC, Botched1 commented
Linked to issue: #3702

2021-11-15 18:12 UTC, AlCalzone commented
Since you merely copied the other file, I'm okay with this. The original file (and by extension this one) doesn't match our style guide however. Would you be willing to help clean it up? I can give you some pointers then.

2021-11-15 19:01 UTC, Botched1 commented
> Since you merely copied the other file, I'm okay with this. The original file (and by extension this one) doesn't match our style guide however. Would you be willing to help clean it up? I can give you some pointers then.

Sure. I don't mind cleaning the new one, or both, up if you have some things you have in mind.

2021-11-15 20:40 UTC, AlCalzone requested changes
Here are several things I'd change - please note that the label and description changes are necessary for almost all params, even if not explicitly highlighted.

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			"description": "The configuration parameter 1 is a read/write parameter with a one-byte field, used to control the status led. if set to on, the status LED will show the status of the latch every
This description seems unnecessary. If anything you might mention the 6 second interval.

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +					"label": "Turns status LED off",
Disable

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +					"label": "Turns status LED on",
Enable

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			"description": "The configuration parameter 2 is a read/write parameter with a one-byte field, used to control the lock’s buzzer. if set to on, the buzzer is enabled and will sound during normal e
```suggestion
			"label": "Buzzer",
```

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			]
```suggestion
			"options": [
				{
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
					"value": 1
				}
			]
```

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			]
...and so on. See https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide for all rules

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +					"label": "Disables secure screen (touch products only)",
"touch products only" would be a good candidate for the description

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			"description": "The configuration parameter 2 is a read/write parameter with a one-byte field, used to control the lock’s buzzer. if set to on, the buzzer is enabled and will sound during normal e
and so on...

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			"description": "The configuration parameter 40 is a write only parameter with a one-byte field, used to request the lock to perform a factory reset back to its default state. this control will cau
```suggestion
			"label": "Reset to Factory Default Setting",
```

2021-11-15 20:40 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +				}
```suggestion
				{
					"label": "Normal Operation",
					"value": 0
				},
				{
					"label": "Reset to Factory Default",
					"value": 1
				},
				{
					"label": "Perform a modified Factory Reset",
					"value": 2
				}
```
(whatever the modified factory reset is)

2021-11-15 23:43 UTC, Botched1 reviewed
This should be closer.

2021-11-15 23:44 UTC, Botched1 commented
@AlCalzone 
I re-did the file. I think it is a lot closer to what the style guide requests.

2021-11-15 23:50 UTC, AlCalzone requested changes

2021-11-15 23:50 UTC, AlCalzone commented on packages/config/config/devices/0x0090/893.json
> +			"description": "",
No empty description please. Remove entirely.

2021-11-16 01:08 UTC, Botched1 reviewed
Getting closer! Removed the blank descriptions.

2021-11-16 08:45 UTC, AlCalzone approved these changes
Looks good, I just mentioned the label for the option to initiate direction detection in the description, since it might not be obvious.

2021-11-16 08:46 UTC, AlCalzone commented
Could you do the same for the 892?

2021-11-16 08:49 UTC, merged

2021-11-16 12:51 UTC, Botched1 commented
> Could you do the same for the 892?

You bet. I should be able to submit that today.