feat(config): add device Inteset WR01Z
AlCalzone/node-zwave-js pull request #3770
Opened 2021-11-21 06:55 UTC by rockosocko

2021-11-21 09:44 UTC, AlCalzone requested changes
Looks good, just one detail:
Parameter labels should be in **Title Case**
https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide?id=labels

2021-11-22 00:35 UTC, rockosocko commented
Not a problem, went ahead and updated the labels.

2021-11-22 08:25 UTC, AlCalzone approved these changes

2021-11-22 08:25 UTC, AlCalzone commented
Thanks!

2021-11-22 08:25 UTC, merged