feat(config): add "Rehau AG" RE.GUARD
AlCalzone/node-zwave-js pull request #3779
Opened 2021-11-22 10:32 UTC by posixx

Add Rehau RE.GUARD Water leakage detector and meter to Z-Wave-JS

2021-11-23 07:46 UTC, AlCalzone requested changes

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +	},
```suggestion
	"associations": {
		"1": {
			"label": "Lifeline",
			"maxNodes": 1,
			"isLifeline": true
		},
		"2": {
			"label": "Valve Status",
			"maxNodes": 5
		},
		"3": {
			"label": "Leakage Alarm",
			"maxNodes": 5
		}
	},
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0 valve always off; 1 user absent/holiday; 2 user present; 3 valve always on",
```suggestion
```
This description is unnecessary because it just duplicates the options.

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +		},
This one should be split into partial parameters: https://zwave-js.github.io/node-zwave-js/#/config-files/partial-parameters

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "pressure drop in kPa",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "pressure drop in kPa",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "how many in one time period",
```suggestion
			"label": "Measurements per Time Period",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0=disable detection, 1=blink LED, 2=blink LED and shut off valve",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0 = no leackage  1 = leakage",
This should be turned into options.

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "max liters single water abstraction if operation mode is 2",
```suggestion
			"label": "Max Single Water Withdrawal (Present Mode)",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "max liter continuous water abstraction if operation mode is 2",
```suggestion
			"label": "Max Continuous Water Withdrawal (Present Mode)",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "max time of single water abstraction if operation mode is 2",
```suggestion
			"label": "Max Single Water Withdrawal Duration (Present Mode)",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "max time of continous water abstraction if operation mode is 2",
```suggestion
			"label": "Max Continuous Water Withdrawal Duration (Present Mode)",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +		},
This and the following parameters look like duplicates of 15-20

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "temporary macro leakage deactivation (e.g. filling pool)",
```suggestion
			"label": "Temporary Macro Leakage Deactivation Time",
			"description": "For example for filling a pool",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0=disable detection, 1=blink LED, 2= blink LED and shut off valve",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0-no leakage, 1- flooding sensor detected leakage",
Turn into options

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0=disable detection, 1=blink LED, 2= blink LED and shut off valve",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "1 = time is set correctly, 0 = time is not set correctly",
Turn into options

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "Counting total operation time internally",
```suggestion
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "0 = disable, 1-168h time after no use, operation mode is changed to 1 (absent)",
```suggestion
			"label": "Auto Absent Timer",
			"description": "After no usage for this long, the operation mode is changed to 1 (absent)",
```
and 0 should be a single option ("Disable")

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "water temperature high threshold for warning of sanitary problems",
```suggestion
			"description": "for warning of sanitary problems",
```
Please change the following descriptions similarly. They shouldn't repeat the label

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +			"description": "automatic adaption of limits, set ids 15-26 to learned values",
```suggestion
			"description": "Automatic adaption of limits, changes parameters 15-26 to learned values.",
```

2021-11-23 07:46 UTC, AlCalzone commented on packages/config/config/devices/0x0413/re_guard.json
> +		}
I guess there should be options for enable and disable/idle?

2021-11-23 12:42 UTC, AlCalzone commented
@posixx I don't think you've handled all review comments

2021-11-23 14:04 UTC, posixx commented
> @posixx I don't think you've handled all review comments

Yes sorry, forgot some. Done now

2021-11-24 07:47 UTC, AlCalzone commented
There were still 2-3 things missing but I fixed them myself. Thanks for the rest!

2021-11-24 07:48 UTC, AlCalzone approved these changes

2021-11-24 07:51 UTC, merged