fix(config): add keemple power plug support
AlCalzone/node-zwave-js pull request #3882
Opened 2021-12-11 14:56 UTC by zollek

Add support for keemple power plug.

I hope this time I don't have so many mistakes.

2021-12-11 15:03 UTC, zollek commented
@zwave-js-bot fix lint

2021-12-14 09:00 UTC, AlCalzone requested changes
Please take a good look at our [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide) and apply it.

There are a bunch of things wrong here, e.g.
- unnecessary / too long descriptions
- Labels should be in **Title Case**
- Typos
- etc.

2022-01-23 18:57 UTC, KloudJack commented
The Keemple KP-SO-02 is a branded Shenzhen Neo NAS-WR01ZE.

I suggest copying that [device's config](https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0258/nas-wr01ze.json) and replacing the manufacturerId, productType, and productId with the Keemple-specific values.

I've a batch of unbranded NAS-WR01ZE's from a chinese distributor on which they accidentally applied the Keemple-brand firmware configuration.

2022-01-24 17:48 UTC, zollek commented
I've shortened it using Style guide and @KloudJack  advice.

Sorry for earlier, didn't know that such a guide exist. Simply copied the manual.

2022-01-25 08:46 UTC, AlCalzone requested changes
Thanks, this is better. Just a few minor changes.

Also, please rename the file to `kp-so-02.json`

2022-01-25 08:46 UTC, AlCalzone commented on packages/config/config/devices/0x041a/keemple_power_plug.json
> +			"description": "Maximum output current limit",
This description seems unnecessary

2022-01-25 08:46 UTC, AlCalzone commented on packages/config/config/devices/0x041a/keemple_power_plug.json
> +			"description": "Current treshold that triggers a report",
dito

2022-01-25 08:46 UTC, AlCalzone commented on packages/config/config/devices/0x041a/keemple_power_plug.json
> +			]
```suggestion
			"$import": "~/templates/master_template.json#state_after_power_failure_off_prev"
```

2022-01-25 08:46 UTC, AlCalzone commented on packages/config/config/devices/0x041a/keemple_power_plug.json
> +					"label": "Active",
```suggestion
					"label": "Enable",
```

2022-01-25 08:46 UTC, AlCalzone commented on packages/config/config/devices/0x041a/keemple_power_plug.json
> +	"manufacturer": "keemple",
```suggestion
	"manufacturer": "Keemple",
```

2022-01-25 08:49 UTC, AlCalzone commented
Oh, I just saw the other PR https://github.com/zwave-js/node-zwave-js/pull/4125/
Let me think about what's the better approach here.

2022-02-01 12:08 UTC, KloudJack commented
> Oh, I just saw the other PR #4125 Let me think about what's the better approach here.

@AlCalzone any update on this?

If importing the whole device config feels too hackish, I could move most of the paramInformation into `~/0x0258/templates/shenzhen_neo_template.json` and import it from there (updating both Shenzhen and Keemple configs).

Almost half of the parameters are `base_enable_disable` which can be imported from the master_template as well.

This way both the NAS-WR01ZE and KP-SO-O2 configs would be structured as follows: https://github.com/zwave-js/node-zwave-js/blob/aff1bc6f1f431e250eb48bf344214a457b0ca290/packages/config/config/devices/0x0371/zw162.json#L2-L35

2022-02-02 21:32 UTC, AlCalzone commented
Eh, sorry this slipped through the cracks. We've decided not to import the entire file - from our experience, it sometimes happens that OEM devices deviate from the original firmwares.

I think we have the most flexibility by having both import from a common template like you proposed. Could you do that?

2022-02-04 15:20 UTC, KloudJack commented
@AlCalzone 

After a quick look at the Shenzhen Neo template and configs, I decided to cleanup the device configs: #4186

At first I'd also moved some of the power plug-specific parameters into the Shenzhen Neo manufacturer template, but after noticing that the NAS-WR01Z and NAS-WR01ZE both have functionally-identical parameters all with (annoyingly) different configurations, I removed them again as it felt out of place to have those in the manufacturer template when they only applied to one device from said manufacturer.

See the following parameter as an example:
https://github.com/zwave-js/node-zwave-js/blob/5827bc98fc9577a6586eb3fd58d62f1d38eb71f2/packages/config/config/devices/0x0258/nas-wr01z.json#L68-L77
https://github.com/zwave-js/node-zwave-js/blob/5827bc98fc9577a6586eb3fd58d62f1d38eb71f2/packages/config/config/devices/0x0258/nas-wr01ze.json#L146-L155

or

https://github.com/zwave-js/node-zwave-js/blob/5827bc98fc9577a6586eb3fd58d62f1d38eb71f2/packages/config/config/devices/0x0258/nas-wr01z.json#L48-L57
https://github.com/zwave-js/node-zwave-js/blob/5827bc98fc9577a6586eb3fd58d62f1d38eb71f2/packages/config/config/devices/0x0258/nas-wr01ze.json#L116-L125

:neutral_face:

I've updated #4125 which uses some master template parameters but no Shenzhen Neo template parameters.

2022-02-09 20:58 UTC, closed without merging