Add initial support for Namron Z-Wave Touch Thermostat 16A
AlCalzone/node-zwave-js pull request #3890
Opened 2021-12-13 00:26 UTC by esplor

This PR only adds productid and some of the paramInformation.
Device included without problems in zwave2mqtt.
Firmware version 1.25

[Link to English instruction manual with CC and params.](https://www.elektroimportoren.no/docs/lib/4512745-Brukerveiledning-5.pdf)

2021-12-13 08:56 UTC, AlCalzone requested changes
> some of the paramInformation

If there are more parameters, we'd appreciate if you add all of them. Otherwise this will lead to support inquiries in the future.

Also, please take a look at our [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide) and update the paramInformation entries accordingly.

2021-12-19 17:18 UTC, esplor commented
All parameters according to documentation are now complete, I rewrote most of the parameters according to the style guide.
Any changes welcome :)

2021-12-19 22:57 UTC, AlCalzone requested changes
Thanks, but this will need another round of changes.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "When detected current is above threshold, relay turns off and sends notification. Allowable range: 0, 5-16",
I'm guessing `0` means disable the function? We usually add a single option for these.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Set buzzer and vibration level.",
unnecessary description

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			]
Please replace with an `$import` of https://github.com/zwave-js/node-zwave-js/blob/a23bffff500afa6cbe8299f8b3c775b1bf18f771/packages/config/config/devices/templates/master_template.json#L367

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Turns off relay and sends notification if temperature is above threshold. Allowable range: 0, 20-60",
I'm guessing `0` means disable the function? We usually add a single option for these.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "When to report temperature relative change actively. Allowable range: 0 (disable), 2-10",
Add a single option for disable instead of mentioning it specifically in the description

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Time interval to report temperature. Allowable range: 0 (disable), 30-28800",
Add a single option for disable instead of mentioning it specifically in the description

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Threshold when to report power change. Allowable range: 0 (disable), 1-100",
etc... carry throughout

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Temperature control hysteresis. Allowable range: 5-20",
Unnecessary description. No need to restate the range if it matches min/maxValue.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Correct room temperature sensor. Allowable range: -10 - 10",
Unnecessary description. No need to restate the range if it matches min/maxValue.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Correct floor temperature sensor. Allowable range: -10 - 10",
Unnecessary description. No need to restate the range if it matches min/maxValue.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Allowable range: 5-100",
Unnecessary description. No need to restate the range if it matches min/maxValue.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Set the mode after drying mode completes.",
Unnecessary description

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Time interval for active report of Meter. Allowable range: 60-2678400",
Unnecessary description. No need to restate the range if it matches min/maxValue.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "Sets OLED brightness, only when active.",
Unnecessary description

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "The timezone that the parameters command adopts is UTC, the timezone need to be set. Allowable range: -12 - 12",
No need to restate the range if it matches min/maxValue.
This sentence also seems to be broken - I'm not sure what its supposed to say.

Maybe the label should just be changed to `UTC Timezone Offset` with a `unit` of `hours`.

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +			"description": "0 - Off, user schedule used. 1 - On, use Energy_Save_Heating temperature set by THERMOSTAT_SETPOINT_SET",
This description seems unnecessary. Especially the values that just restate the options below

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +					"label": "Energy save mode off",
```suggestion
					"label": "Disable",
```

2021-12-19 22:57 UTC, AlCalzone commented on packages/config/config/devices/0x0438/touch-thermostat-16a.json
> +					"label": "Energy save mode on",
```suggestion
					"label": "Enable",
```

2021-12-31 10:05 UTC, AlCalzone commented
@esplor ping :)

2022-05-11 07:43 UTC, ThoStaKa commented
I can see that the development has been stopped. Unfortunately, I do not have the competence to develop my own configuration file. 

However, this product seems to be a clone of Sunricher "SR-ZV9092A-EU". Could this maybe help? 
https://products.z-wavealliance.org/products/4289
https://products.z-wavealliance.org/ProductManual/File?folder=&filename=product_documents/4289/SR-ZV9092A%20instructionRelease.pdf

Namron manual here:
"https://www.elektroimportoren.no/docs/lib/4512744-Brukerveiledning-5.pdf"

2022-06-04 19:18 UTC, esplor commented
> I can see that the development has been stopped. Unfortunately, I do not have the competence to develop my own configuration file.
> 
> However, this product seems to be a clone of Sunricher "SR-ZV9092A-EU". Could this maybe help?

@ThoStaKa 
Indeed, thank you! Even found a undocumented parameter (26 - Window open).
I've tested the SR-ZV9092A-EU config file in zwavejs2mqtt and I haven't found any problems.

New PR coming soon.

2022-06-04 20:48 UTC, esplor commented
@zwave-js-bot fix lint

2022-06-07 13:11 UTC, AlCalzone reviewed
Great, thanks for coming back to this!

2022-06-07 13:11 UTC, AlCalzone approved these changes

2022-06-07 13:15 UTC, merged