fix(config): Update CT100 Device Config FIle
AlCalzone/node-zwave-js pull request #3911
Opened 2021-12-15 21:00 UTC by Indianb0y016

Updated CT100 Config file. Device is fundamentally the same as the CT100-Plus, with a few differences. Crosschecked with the OpenZWave device config for reference and everything is the same.

PS. It is my first time pulling a proper PR so I apologize if this is not fully completed or acceptable. 
However, the file was tested on my ZwaveJS instance and worked fine, providing critical functions to the device in question.

2021-12-15 21:06 UTC, Indianb0y016 commented
@zwave-js-bot fix lint

2021-12-16 08:00 UTC, AlCalzone requested changes
Please check out the [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide) and update the param definitions accordingly. Some examples below:

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +			"description": "Enable or disables Multicast",
```suggestion
			"label": "Multicast",
```

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +					"label": "Multicast disabled",
```suggestion
					"label": "Disable",
```

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +					"label": "Multicast enabled",
```suggestion
					"label": "Enable",
```

**Please update the other params with similiar options accordingly**

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +			"description": "Enable or disables Multicast",
Descriptions that merely restate the label should be removed

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +			"maxValue": 255,
These don't match up with the options

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +			"maxValue": 255,
These don't match up with the options

2021-12-16 08:00 UTC, AlCalzone commented on packages/config/config/devices/0x0098/ct100.json
> +			"maxValue": 255,
These don't match up with the options

2022-06-03 00:07 UTC, closed without merging