Update Z-Uno definition
AlCalzone/node-zwave-js pull request #3925
Opened 2021-12-18 00:39 UTC by robin-thoni

Add missing parameters for the Z-Uno.

Manufacturer doc: https://z-uno.z-wave.me/z-wave/configuration-parameters/

2021-12-18 00:49 UTC, robin-thoni commented
@zwave-js-bot fix lint

2021-12-18 15:48 UTC, AlCalzone requested changes
The labels are unnecessarily verbose. Please shorten them and move the additional information into the `"description"` field.

Also, param labels should be in `Title Case`

2021-12-18 17:55 UTC, robin-thoni commented
Done! Thanks for the review!

2021-12-19 09:16 UTC, AlCalzone approved these changes

2021-12-19 09:16 UTC, merged