feat(config): Add Zooz zse43 config file
AlCalzone/node-zwave-js pull request #3979
Opened 2021-12-28 23:34 UTC by Botched1

Add config file for Zooz zse43 tilt/shock sensor

2021-12-28 23:41 UTC, Botched1 commented
@zwave-js-bot fix lint

2021-12-29 02:18 UTC, blhoward2 requested changes
Great job on this so far. A few minor comments and one parameter that I suspect changed in the production firmware based on what Zooz sent me.

2021-12-29 02:18 UTC, blhoward2 commented on packages/config/config/devices/0x027a/zse43.json
> +			"#": "1",
In the production firmware, this isn't an enable/disable parameter and instead has three options. Please update.

https://www.support.getzooz.com/kb/article/817-zse43-tilt-shock-xs-sensor-advanced-settings/

2021-12-29 02:18 UTC, blhoward2 commented on packages/config/config/devices/0x027a/zse43.json
> +			"valueSize": 2,
This should be size 4.

2021-12-29 02:18 UTC, blhoward2 commented on packages/config/config/devices/0x027a/zse43.json
> +			"valueSize": 2,
This should be size 4 as well.

2021-12-29 02:18 UTC, blhoward2 commented on packages/config/config/devices/0x027a/zse44.json
> +			"label": "Temperature Offset - 0=-10, 100=0, 200=+10",
This is a particularly screwy parameter, but put that information in the description not the label.

2021-12-29 02:18 UTC, blhoward2 commented on packages/config/config/devices/0x027a/zse44.json
> +			"label": "Humidity Offset - 0=-10, 100=0, 200=+10",
Same, the description is the right place for further explanation.

2021-12-29 03:11 UTC, blhoward2 approved these changes, later dismissed

2021-12-29 10:00 UTC, AlCalzone approved these changes
OK with my changes

2021-12-29 10:04 UTC, merged