fix(config): ZWN-RSM2-PLUS #2280
AlCalzone/node-zwave-js pull request #4046
Opened 2022-01-05 21:31 UTC by ronytomen

Fixes: #2280

- Force Endpoint 0 for Group 1 Associations Lifeline so that CurrentValue
  status reports are sent and processed.
- Define the one configuration parameters options as per mfg data

---

Did some experimentation to get this device to report manual local change (someone turns the switch off or on) and found that setting the Endpoint Target to 0 for Group 1 Association (Lifeline) did the trick.  I only found one other example of Endpoint usage in device configurations, so I hope I got this correct.

2022-01-05 21:34 UTC, ronytomen commented
<img width="1574" alt="Screen Shot 2022-01-05 at 4 32 53 PM" src="https://user-images.githubusercontent.com/5140624/148292698-af2fe422-72e1-4d31-b040-737a884942ea.png">

For the record, attached screenshot of working group association with endpoint target.

2022-01-06 08:26 UTC, AlCalzone commented
I think the documentation of that config setting isn't up to date. You should be able to achieve the same result by setting `"multiChannel": true` on the first association group without dabbling with endpoint associations.

2022-01-06 08:37 UTC, AlCalzone requested changes
Please try the suggestion, re-interview your device and post a driver log of that. I'm fine with keeping it this way if it won't work, but ideally it should.

2022-01-06 13:47 UTC, ronytomen commented
> I think the documentation of that config setting isn't up to date. You should be able to achieve the same result by setting `"multiChannel": true` on the first association group without dabbling with endpoint associations.

Thank you!  I was trying to figure this out, but decided to post the PR for some sage advise.  I will revise, test and update in the next few days.

2022-01-09 03:53 UTC, ronytomen commented
Multi Channel suggestion implemented, re-interviewed and confirmed working.  Attached is the Interview log for node 38.

[node_38.log](https://github.com/zwave-js/node-zwave-js/files/7834439/node_38.log)

2022-01-09 16:15 UTC, AlCalzone commented
Looks OK, does it work for you?

2022-01-09 16:42 UTC, ronytomen commented
Just did some more testing.

1.  Cleared the current associations
2. Re-interviewed

No group associations were created and the configuration parameter does not show up.  
<img width="1450" alt="Screen Shot 2022-01-09 at 11 35 37 AM" src="https://user-images.githubusercontent.com/5140624/148691733-a74032c0-9117-41e7-a89b-bff5144ceba6.png">
![Screen Shot 2022-01-09 at 11 35 15 AM](https://user-images.githubusercontent.com/5140624/148691735-b6049d55-56b8-42c3-9c5a-e53b8b9a047b.png)

It is using the modified device configuration, debug for node 38 attached.
[node_38_debug.txt](https://github.com/zwave-js/node-zwave-js/files/7835474/node_38_debug.txt)

2022-01-09 16:44 UTC, 1085986063a commented on packages/config/config/devices/0x011a/zwn-rsm2.json
> +				}
packages/config/config/devices/0x011a/zwn-rsm2.json

2022-01-09 16:51 UTC, AlCalzone commented
Weird, your log did show an existing multi channel association

2022-01-09 17:00 UTC, ronytomen commented
I don't think that interview had the associations removed.  Let me get the interview with the associations removed before starting.

2022-01-09 17:01 UTC, ronytomen commented
I wanted to note that either the Lifeline or per switch association works, but only if Target Endpoint 0 is specified.   Otherwise the status of each of the switches do not update. 

<img width="911" alt="lifeline_association_working" src="https://user-images.githubusercontent.com/5140624/148692451-3d9a6c60-5123-4fa1-9cc9-86e579bf5411.png">
<img width="842" alt="switch_association_working" src="https://user-images.githubusercontent.com/5140624/148692452-98e56628-dad4-460f-8fc8-604e42b010ce.png">

2022-01-09 17:07 UTC, ronytomen commented
Here is the log for Node 38 Interview with associations cleared.  Result, no associations created.
[node_38_interview_20210109_1.log](https://github.com/zwave-js/node-zwave-js/files/7835515/node_38_interview_20210109_1.log)

2022-01-09 19:55 UTC, AlCalzone commented
Heh, the device claims it supports Multi Channel Association V2. However, being able to use 0 as the target endpoint was only added in V3 of that CC, so the driver won't do it.

We need to overwrite the reported version aswell, please add that to your config file:
```jsonc
"compat": {
	"commandClasses": {
		"add": {
			// The device needs a multi channel lifeline association (target endpoint 0),
			// but only reports support for V2, which doesn't allow this.
			"0x8e": {
				"version": 3
			}
		}
	}
}
```

2022-01-09 21:58 UTC, ronytomen commented
Updated device file and tested.  Works as expected creating the correct Lifeline Association with a EndPoint Target 0.

😀

2022-01-10 08:48 UTC, AlCalzone approved these changes

2022-01-10 08:48 UTC, merged