added inclusion, excelusion and reset instructions
AlCalzone/node-zwave-js pull request #4111
Opened 2022-01-19 20:07 UTC by SimpleUserHA

added inclusion, excelusion and reset instructions from http://manuals-backend.z-wave.info/make.php?lang=en&sku=DEVE9356&cert=ZC08-15020003

2022-01-22 12:10 UTC, AlexCPU commented on packages/config/config/devices/0x0002/mt02650.json
> +		"exclusion": "Click on the middle button will confirm inclusion or exclusion and wakeup the device for wireless communication./nA long push for 3 seconds on the middle buttons enters and leaves the
Newline should be \n

2022-01-23 11:34 UTC, AlCalzone requested changes
What @AlexCPU said

2022-01-23 22:27 UTC, SimpleUserHA commented
thanks for the remarks, newline fixed as requested.

2022-01-25 10:00 UTC, AlCalzone approved these changes

2022-01-25 10:00 UTC, merged