Add a missing parameter to a device
AlCalzone/node-zwave-js pull request #4176
Opened 2022-02-01 21:43 UTC by Spilarix

Parameter described in the documentation : https://aeotec.freshdesk.com/helpdesk/attachments/6102433780

2022-02-01 22:23 UTC, AlCalzone requested changes
Looking at the changelog in the linked manual, it seems that this parameter was added in a later firmware revision. Can you please contact Aeotec and verify in which firmware this was added?

That way we can avoid users with an older firmware getting confused by a non-existant param.

2022-02-02 07:57 UTC, Spilarix commented
> Looking at the changelog in the linked manual, it seems that this parameter was added in a later firmware revision. Can you please contact Aeotec and verify in which firmware this was added?
> 
> That way we can avoid users with an older firmware getting confused by a non-existant param.

Done : 3.25 or later.

2022-02-02 13:26 UTC, AlCalzone approved these changes

2022-02-02 13:26 UTC, AlCalzone commented
Great, thanks!

2022-02-02 13:29 UTC, merged