Update hs1sa-z.json
AlCalzone/node-zwave-js pull request #4244
Opened 2022-02-16 20:33 UTC by alfakenzo

Updated some Infos

PR description here

2022-02-17 21:18 UTC, AlCalzone requested changes

2022-02-17 21:18 UTC, AlCalzone commented on packages/config/config/devices/0x0260/hs1sa-z.json
> +		"overwiew": "The smart smoke sensor detects smoke, and sends an alarm signals to alert of danger. When the smart smoke sensor detects smoke, it will send an alarm notification to your controller th
See https://zwave-js.github.io/node-zwave-js/#/config-files/file-format?id=metadata, we have only a limited set of fields at the moment. Overview is not one of them.

2022-02-17 21:18 UTC, AlCalzone commented on packages/config/config/devices/0x0260/hs1sa-z.json
> +		"wakeup": "Wake up Information\n- Wake up Notification is transmitted every 24 hours by default. Wake up Notification is transmitted after Notification Report is Transmitted."
`wakeup` should indicate how to wake the device up manually, not describe what this does.

2022-04-16 15:44 UTC, blhoward2 commented
Since this has been abandoned, I've just deleted the unsupported fields so it can be merged.

2022-04-20 10:32 UTC, AlCalzone submitted a review, later dismissed

2022-04-20 10:33 UTC, AlCalzone commented
@zwave-js-bot fix lint

2022-04-20 10:34 UTC, AlCalzone approved these changes

2022-04-20 10:37 UTC, merged