Add Thermofloow TF016 v1.92 to database.
AlCalzone/node-zwave-js pull request #4260
Opened 2022-02-20 10:24 UTC by toffyrn

Version 1.92 is a version of TF016 to show temperature from both internal
sensor and floor sensor. It also provides current relay state.

Changes are imported using "yarn run config import -s oh -Dd --ids 896"
and relevant changes manually merged into tf016.json.

2022-02-20 10:27 UTC, toffyrn commented
I have unfortunately not tested this myself. I am running zwave-js within home assistant os and found no simple guide on how to replace database files on such a system. Any pointers on how to do that would be appreciated.

I do not have any prior expertise in ZWave config, so I am unsure if there are any risk to other devices if merging this untested. Please let me know.

2022-02-20 12:50 UTC, AlCalzone requested changes
Using zwavejs2mqtt you can test the file as described here:
https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files

A few changs please:

2022-02-20 12:50 UTC, AlCalzone commented on packages/config/config/devices/0x019b/tf016.json
> +			"description": "Defines operation mode of the thermostat",
This is an [unnecessary](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide?id=parameter-descriptions) description, please remove.

2022-02-20 12:50 UTC, AlCalzone commented on packages/config/config/devices/0x019b/tf016.json
> +			"description": "Determines which sensor is in use",
Maybe it would make more sense to give the options a better label?

2022-02-20 12:50 UTC, AlCalzone commented on packages/config/config/devices/0x019b/tf016.json
> +			"description": "The resistance (type) of the external room sensor.",
Which is it? Floor sensor or external room sensor? Also I'm leaning towards unnecessary description.

2022-02-20 12:50 UTC, AlCalzone commented on packages/config/config/devices/0x019b/tf016.json
> +			"description": "Power mode. 0 is always off, 10 is always on.",
```suggestion
			"label": "Power mode",
```
and convert _0 is always off, 10 is always on_ into options.

2022-02-20 14:43 UTC, toffyrn commented
Thanks a lot @AlCalzone for the comments. I will try migration to zwavejs2mqtt, test the file, update the review and get back here.

2022-03-08 18:02 UTC, toffyrn commented
I have moved to zwavejs2mqtt, but this database does not seem to have any effect on the device ability to send updates to controller for the additional entities.
Closing this pull request.

2022-03-08 18:02 UTC, closed without merging