Adding event notifications for the multilevel switch command class
AlCalzone/node-zwave-js pull request #4282
Opened 2022-02-25 17:36 UTC by reubenbijl

Hi,

Would really appreciate some feedback on this   so I can keep working on it.

2022-02-25 17:42 UTC, reubenbijl commented
@zwave-js-bot fix lint

On Sat, 26 Feb 2022 at 6:40 AM, zwave-js-assistant[bot] <
***@***.***> wrote:

> 🚧 It seems like this PR has lint errors 🚧
>
> I should be able to fix them for you. If you want me to, just comment
> @zwave-js-bot fix lint
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zwave-js/node-zwave-js/pull/4282#issuecomment-1051058899>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOMN63CBI2FC6ETAWEPL2DU465JZANCNFSM5PK3Q5HQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-25 22:18 UTC, AlCalzone commented
This doesn't pass the linter:
```
/home/runner/work/node-zwave-js/node-zwave-js/packages/zwave-js/src/lib/node/Node.ts
Error:   2826:9  error  'sourceEndpoint' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

and tests are failing too - you can run them locally using `yarn test` to figure out what's wrong.

2022-02-25 22:29 UTC, AlCalzone requested changes

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +		if (node.deviceConfig?.compat?.treatBasicSetAsEvent) {
MultilevelSwitchCC should have a separate compat flag (not named `...Basic...`)

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +	public readonly duration: Duration | undefined;
This seems wrong. A `MultilevelSwitchCCSet` doesn't have a `currentValue` property and its properties shouldn't be readonly.

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
>  		}
Changing the code that sends `MultilevelSwitchCCSet` isn't necessary to understand them when they are received.

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +		}
Let's not water down the meaning of the event value too much, it should be limited to the value received via a Set command.
I'd prefer having start/stopLevelChange as a new `notification` type, like for Powerlevel CC and Entry Control CC - see point 3. in my comment in the issue.

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +			this.getEndpoint(command.endpointIndex ?? 0) ?? this;
This isn't used

2022-02-25 22:29 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +			return this.handleMultilevelSwitchCommand(command);
That's fine

2022-02-25 22:30 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
>  		}
This is probably why tests are failing.

2022-03-03 09:11 UTC, reubenbijl commented
@AlCalzone  Thanks for the feedback, I believe that I've made most of the changes you've suggested. I'd be keen if you have any thoughts on the event structure, with the way I'm passing the event type through the notification.

2022-03-11 20:16 UTC, AlCalzone requested changes
Sorry for taking so long to review this. A few more changes please.

2022-03-11 20:16 UTC, AlCalzone commented on maintenance/schemas/device-config.json
> +				"treatMultilevelSwitchAsEvent": {
```suggestion
				"treatMultilevelSwitchSetAsEvent": {
```
(rename the other occurences similarly)

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +	eventType: MultilevelSwitchCommand;
```suggestion
	eventType: MultilevelSwitchCommand.StartLevelChange | MultilevelSwitchCommand.StopLevelChange;
```
would be more specific

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +	public targetValue: number | undefined;
`targetValue` in a MultilevelSwitchCCSet is always defined.

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +		];
so this is not necessary (and doesn't make sense)

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +				this.targetValue = parseNumber(this.payload[0]);
```suggestion
			if (this.payload.length >= 2) {
```

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +				this.targetValue = parseNumber(this.payload[0]);
Only the duration is optional and it is guaranteed to be at index 1 if the payload is long enough.

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +	public eventType: MultilevelSwitchCommand;
The class instance already identifies this command, no need for an extra variable. Just handle this like you handle the StopLevelChange command.

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +				pick(command, ["eventType", "direction"]),
```suggestion
				{ eventType: MultilevelSwitchCommand.StarLevelChange, direction: command.direction },
```

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/node/Node.ts
> +				pick(command, ["eventType", "direction"]),
(see above for explanation)

2022-03-11 20:16 UTC, AlCalzone commented on packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
> +	public eventType: MultilevelSwitchCommand;
Same goes for the other 2-3 lines where you reference this.

2022-03-13 06:18 UTC, reubenbijl commented
@zwave-js-bot fix lint

2022-03-14 14:28 UTC, AlCalzone approved these changes, later dismissed

2022-03-14 14:56 UTC, AlCalzone approved these changes

2022-03-14 14:56 UTC, AlCalzone commented
Thanks a lot!

2022-03-14 14:56 UTC, merged