Add values for Alarm and Doorbell Sound Selection
AlCalzone/node-zwave-js pull request #4400
Opened 2022-03-21 21:25 UTC by jaym25

Add values for Alarm and Doorbell Sound Selection

2022-03-21 21:51 UTC, AlCalzone requested changes
Now, this is better :) A few nits though.
Also, do you know if this was added in a specific firmware version or do these additional values exist for all firmwares?

2022-03-21 21:51 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-ab01z.json
> +					"value": 255
please update the `maxValue` to match or (even better) remove min/maxValue and add `"allowManualEntry": false` before the options.

2022-03-21 21:51 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-ab01z.json
> +			"options": [
Please add `"allowManualEntry": false` before the options.

2022-03-21 21:51 UTC, AlCalzone commented on packages/config/config/devices/0x0258/nas-ab01z.json
> +			"options": [
dito

2022-03-22 05:13 UTC, jaym25 commented
This is a device I have been using in Home Assistant.  The firmware version is 2.102.  The additions come from the open ZWave configuration (with minor changes) that I have been using before switching to Z-Wave JS.  Some changes come from the user manual.  I did listen to the all the sounds and the descriptions are correct.  I cannot assure you the sounds are not different in different firmware revisions.

I also cannot figure out how to edit the revisions using Gitpod...

For parameter 2, the available settings are actually 0-3,255 so minValue and maxValue alone will not work.
I am concerned about using ("allowManualEntry": false) as it may prevent the values being set from Home Assistant automation code.  This would definitely cause problems.
If ("allowManualEntry": false) actually prevents changes from automation code, what option would be available to allow 255 as an additional setting in parameter 2?

If this is too much trouble for you, I will go ahead and close this request per your instruction.

2022-03-22 05:37 UTC, jaym25 commented
Also, from the user manual:
Parameter 5 - Alarm Sound default is 10
Parameter 6 - Doorbell Sound default is 9
The existing config file has them reversed...

2022-03-22 07:33 UTC, AlCalzone commented
> For parameter 2, the available settings are actually 0-3,255 so minValue and maxValue alone will not work.

That's precisely what allowManualEntry does. You can still set it from automations, but UIs that respect the flag will show you a dropdown instead of a free text field with auto-complete. Having maxValue=3 won't let you set 255 though.

I know that it's hard/nearly impossible to track down which firmware changed which parameters for some of these asian manufacturers, so I'm fine with merging the changes.

> I will go ahead and close this request per your instruction.

Nonono, I just want to make sure everything is correct, as we put a lot of effort in having the best (and correct) config files. Just edit the file in your fork again, adding `"allowManualEntry"`. That will update this PR and I can merge.

2022-03-22 14:29 UTC, jaym25 commented
I think I got it this time...  I hope!

2022-03-31 19:04 UTC, AlCalzone approved these changes

2022-03-31 19:08 UTC, merged