fix(config): param 4 add value 3 for Zooz Zen16
AlCalzone/node-zwave-js pull request #4404
Opened 2022-03-26 20:50 UTC by GaTechThomas

Fixes #4403.

2022-03-27 09:12 UTC, AlCalzone requested changes
Small typo, I'll fix this myself

2022-03-27 09:12 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"maxValue": 3,
```suggestion
			"maxValue": 2,
```

2022-03-27 09:12 UTC, AlCalzone approved these changes

2022-03-27 09:13 UTC, AlCalzone commented
Thanks!

2022-03-27 09:16 UTC, merged

2022-03-27 15:37 UTC, GaTechThomas commented
Good catch on the maxValue. On that point, param 2 and param 3 firmware <= 1.1 both have maxValue 3 when it should be 2. Is that a significant item? This was existing in the previous version of the code - should it be a new issue?

2022-03-29 09:11 UTC, AlCalzone commented
Yeah, these should be corrected. Wonder why our linter doesn't catch those.