New keemple devices
AlCalzone/node-zwave-js pull request #4503
Opened 2022-04-23 19:13 UTC by pawkakol1

Templates for Keemple light switch devices:
- KP-SW-07
- KP-SW-08

2022-04-23 21:57 UTC, pawkakol1 commented
@zwave-js-bot fix lint

2022-04-24 21:51 UTC, pawkakol1 commented
@zwave-js-bot fix lint

2022-04-25 07:42 UTC, AlCalzone commented
Why close?

2022-04-25 16:02 UTC, pawkakol1 commented
I closed it because I had problems with run checks on mobile app. I planed open pull request today again, but I see I don't need to

2022-04-27 10:11 UTC, AlCalzone requested changes
A few changes, I'll do them myself

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-07.json
> +			"description": "Lifeline (primary controller)",
```suggestion
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-07.json
> +			"description": "Scene control",
```suggestion
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-07.json
> +			"description": "Define how the Switch reacts after the power supply is back on",
```suggestion
```
The template exists to to have consistent labels for this functionality across devices.

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-07.json
> +			"description": "Touch Switch can send notifications to association device when state of Touch Switch’s load change.",
```suggestion
			"label": "Load Status Change Reports",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-07.json
> +					"label": "Enabled only when Load condition is not changed by Z-WAVE Command",
```suggestion
					"label": "Enabled (manual control only)",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Lifeline (primary controller)",
```suggestion
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Scene control",
```suggestion
			"label": "Scene Control",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Endpoint 1: Switch status report",
```suggestion
			"label": "Switch 1 Status",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Endpoint 2: Switch status report",
```suggestion
			"label": "Switch 2 Status",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Define how the Switch reacts after the power supply is back on",
```suggestion
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +			"description": "Touch Switch can send notifications to association device when state of Touch Switch’s load change.",
```suggestion
			"label": "Load Status Change Reports",
```

2022-04-27 10:11 UTC, AlCalzone commented on packages/config/config/devices/0x041a/kp-sw-08.json
> +					"label": "Enabled only when Load condition is not changed by Z-WAVE Command",
```suggestion
					"label": "Enabled (manual control only)",
```

2022-04-27 10:12 UTC, AlCalzone approved these changes, later dismissed

2022-04-27 10:12 UTC, AlCalzone approved these changes

2022-04-27 10:17 UTC, merged