Update Zooz ZEN30 parameters for newest firmware
AlCalzone/node-zwave-js pull request #4510
Opened 2022-04-26 17:50 UTC by shbatm

Update Zooz ZEN30 parameter options to include paramaters 28, 29, and 30, added in recent firmware updates.

https://www.support.getzooz.com/kb/article/468-zen30-double-switch-advanced-settings/
https://www.support.getzooz.com/kb/article/393-zen30-double-switch-change-log/

2022-04-27 10:04 UTC, AlCalzone requested changes
A few changes to comply with the style guide please. I'm not sure how obvious it is that the scenes can be triggered with double taps. If that's a concern, we can mention it in the description, but we should avoid writing "enable/disable" tree times.

2022-04-27 10:04 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +			"description": "Enable or disable scene control functionality for quick double tap triggers on the dimmer.",
```suggestion
			"label": "Scene Control (Dimmer)",
```

2022-04-27 10:04 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +			"description": "Enable or disable scene control functionality for quick double tap triggers on the relay button.",
```suggestion
			"label": "Scene Control (Relay)",
```

2022-04-27 10:04 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +					"label": "Scene control enabled",
```suggestion
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
```

2022-04-27 10:04 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +					"label": "Scene control enabled",
```suggestion
					"label": "Disable",
					"value": 0
				},
				{
					"label": "Enable",
```

2022-04-27 11:07 UTC, shbatm commented
> A few changes to comply with the style guide please. I'm not sure how obvious it is that the scenes can be triggered with double taps. If that's a concern, we can mention it in the description, but we should avoid writing "enable/disable" tree times.

Sounds good, I just copied from the ZOOZ release notes.

2022-04-28 06:56 UTC, AlCalzone approved these changes

2022-04-28 06:56 UTC, merged

2022-05-02 16:17 UTC, kernelpanic85 commented
I have some ZEN 30 switches running the new firmware and took a look after deploying the update. The new options show under Configuration undefined rather than with the other options under Configurationv1. Also they aren't showing any names or descriptions. Screenshot below:

![image](https://user-images.githubusercontent.com/80057019/166268852-0890a392-e2cc-4172-91c7-cfbd35ad4d15.png)

2022-05-02 18:51 UTC, AlCalzone commented
Did you re-interview your device?

2022-05-02 19:58 UTC, kernelpanic85 commented
Ah, that did it, thanks!

![image](https://user-images.githubusercontent.com/80057019/166316639-c4e9dda1-3b0d-4f62-93f0-68401921d3da.png)