fix(config): zooz: use templates wherever possible
AlCalzone/node-zwave-js pull request #4619
Opened 2022-05-13 16:12 UTC by kaechele

As promised in #4496 I have reworked the entire Zooz config subfolder to make use of templates wherever possible.

I recognize that this is a massive changeset, so it will take some time to review. Any help appreciated. Many changes follow simple patterns so once you get the hang of it it should become straightforward. I found having a mental model of how the `base_` templates work helps to speed up the review. E.g. `base_enable_disable` is `0 = Disable` and `1 = Enable` with a `defaultValue` of `0` (Disable).
It is also largely untested as I do not own most of the devices touched by these changes. Any guidance on how to best test this is appreciated. I'm willing to spend the effort on testing.

Happy to incorporate any feedback. E.g. you may want me to shuffle stuff around in the `master_template.json` or `zooz_template.json`. Especially the latter is getting a bit crowded by now that I was thinking maybe alphabetically sorting stuff would make sense. Zooz devices do have quite an overlap (and often not entirely consistent) it turns out.
Also Zooz documentation is of varying quality, especially the older the device is. I would have fixed it for them if their Knowledge base had been a Wiki.
I have cross referenced the documentation for each device many times to ensure that what I'm swapping out for a template is actually accurately represented by that template.
However, especially historic documentation is often unavailable and the change logs often merely allude to what parameters were changed and in which ways. So I've done my best to keep that information intact.

2022-05-17 08:47 UTC, AlCalzone commented
Wow, this is great! I'll try to get to this soon, unless @blhoward2 beats me to it. Currently I'm caught up in my own massive undertaking over at https://github.com/zwave-js/node-zwave-js/pull/4614

2022-05-25 20:34 UTC, kaechele commented
Just a little side rant: Zooz published OTA firmware updates for the ZEN72/77 dimmers and because after version 1.01 there was 10.0 the new version is now - you guessed it - 2.0 🤦🏼‍♂️

2022-05-31 08:02 UTC, AlCalzone requested changes
Really great work! I have a couple of requests, though nothing major.

---

🚨🚨🚨
Whatever you do with this: **PLEASE NO FORCE-PUSH** :)
You can make a mess, merge stuff, I don't care. This will all get squashed into one nice commit later.
Force-push will make it impossible to follow the changes you do after the commit, so I have to look at everything again.
🚨🚨🚨

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +			}
These labels need to be shortened (a lot). Is there a way we can move some of the explanation into the parameter description and break down the option labels to the bare minimum?

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
>  		"label": "Smart Bulb Mode: Dimming Reporting Behavior",
Same goes for the options of this one

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"label": "Enable Double-Tap behavior",
```suggestion
		"label": "Double-Tap Behavior",
```
we try to avoid Enable/Disable in the param label

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +				"label": "Double-Tap Disabled, Single-Tap to Full Brightness",
```suggestion
				"label": "Enable Double-Tap",
				"value": 0
			},
			{
				"label": "Disable Double-Tap, Single-Tap to Last Brightness",
				"value": 1
			},
			{
				"label": "Disable Double-Tap, Single-Tap to Full Brightness",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +				"label": "Double-Tap Disabled, Single-Tap to Full Brightness",
this makes it easier to see at first glance

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"description": "Disables inclusion/exclusion commands on paddle for use with scene controls."
I thought we changed the label to avoid mentioning "paddle" for switches? Might make sense to change it  in the description too.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"description": "Send command to associated device.",
Is it obvious which command is sent? Basic Set?

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen07.json
>  			"description": "Set the time to automatically turn off",
```suggestion
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/2",
This won't work. `$import` is resolved before `$if` and resolves to the first found entry, not all of them. Unfortunately, you'll have to keep the verbose variant or move the definitions into the template and import from there, to keep the conditional logic.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"label": "Switch 3: Type"
dito

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"description": "Sets the time after which relay 1 turns off once it has been turned on. Using the units defined in parameter 15."
Might make sense to reorder the parameter definitions so 15 comes between 6 and 7. Same for the others.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/12",
See comment above, this won't work sadly

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/12",
See comment above, this won't work sadly

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/15",
This is okay, as long as there is only one definition for param 15

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen17.json
> +			"$import": "#paramInformation/2",
sorry, nope. Move definitions to the template.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen20.json
>  			"description": "Choose how you want your Power Strip to report power consumption to your hub",
```suggestion
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen20.json
> +			"label": "CH1 Auto Turn-Off Setting"
These labels are different from the ones below, param 8ff. Please change here to match the ones below.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen20.json
>  			"description": "Enable / Disable Physical Button Functionality",
One of the previous files had a different (better) description. Maybe moving this to a template makes sense?

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen25.json
> +			"unit": "Amperes",
https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide?id=units
Please prefer the technical units

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +			"description": "Brightness level for the dimmer to come on to at single tap.",
I'd make the label "Dimmer Brightness After Single Tap" or something simple like this and remove the description.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen30.json
> +					"label": "Last brightness level",
```suggestion
					"label": "Last non-zero brightness",
```
or something like that. Brightness level is a bit redundant.

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN1. Choose the input/switch type you want to connect to the IN1 terminal. Default: momentary switch"
Unnecessary description

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN2. Choose the input/switch type you want to connect to the IN2 terminal. Default: momentary switch"
Unnecessary description

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN3. Choose the input/switch type you want to connect to the IN3 terminal. Default: momentary switch"
Unnecessary description

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN4. Choose the input/switch type you want to connect to the IN4 terminal. Default: momentary switch"
Unnecessary description

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "1-127 = seconds, 128-254 = 1-127 minutes",
For consistency with other configurations I prefer
```suggestion
			"description": "1...127 = seconds, 128...254 = minutes (minus 127)",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "1-127 = seconds, 128-254 = 1-127 minutes",
For consistency with other configurations I prefer
```suggestion
			"description": "1...127 = seconds, 128...254 = minutes (minus 127)",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
>  			"unit": "seconds",
```suggestion
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
>  			"unit": "seconds",
```suggestion
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen31.json
>  			"description": "Click/toggle the connected switch 1 time to trigger a scene.",
These labels/descriptions don't match the style guide. In the Fibaro files we have these labels that could be adopted here:
```suggestion
			"label": "Input 1: Send Scenes (Key Pressed 1x)"
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen32.json
> +			"description": "Determines whether an on/off report is sent and LED changes on button press, when the relay is disabled"
This info should be merged into the label

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse08.json
>  			"description": "Delay (in seconds) before close signal will be sent",
```suggestion
			"unit": "seconds",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse08.json
>  			"description": "The value that will be set when the sensor is triggered",
description seems unnecessary

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse09.json
>  			"description": "delay after motion before turning OFF",
I'm sure there is a better label/description combination for this somewhere else

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse09.json
>  			"description": "Light level change to be reported.",
```suggestion
			"label": "Light Reporting Threshold",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse18.json
> +			"description": "3 seconds is added to the value you set (eg. default value of 27 equals 30 seconds)",
```suggestion
			"description": "3 seconds are added to the configured value (e.g. 27 equals 30 seconds)",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse29.json
>  			"label": "Enable / Disable Motion Reports",
```suggestion
			"label": "Send Motion Reports",
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse33.json
> +				}
```suggestion
					"label": "30 seconds",
					"value": 1
				},
				{
					"label": "60 seconds",
					"value": 2
				},
				{
					"label": "5 minutes",
					"value": 3
				},
				{
					"label": "Until battery drains",
					"value": 255
				}
```

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse40.json
>  			"description": "Set the trigger interval for motion sensor re-activation.",
I commented on this in a different file where it was called differently. This is one of the parameters that are used often (not just limited to Zooz) and very inconsistent. I like something like "Motion Detection Timeout" or "Motion Re-Trigger Timeout"

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zse41.json
> +			"description": "When enabled, the device will report open when the magnet is near"
I guess this should rather use NO/NC instead of referring to an unknown normal state.
0: Normally Closed (Report open when magnet is away)
1: Normally Open (Report open when magnet is near)

2022-05-31 08:02 UTC, AlCalzone commented on packages/config/config/devices/templates/master_template.json
> +		"defaultValue": 1,
This is not only used in Zooz files. If you need to change the default for Zooz, please import this template from the zooz template and modify the default value there.

2022-05-31 11:11 UTC, kaechele commented on packages/config/config/devices/templates/master_template.json
> +		"defaultValue": 1,
Correct me if I'm wrong but the defaultValue of 3 isn't even a valid value for this setting. So this is meant more as a bugfix. May be better suited for an individual pull request to give the change more visibility if it is, in fact, a true fix for a bug.

2022-05-31 11:54 UTC, kaechele commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +			}
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/cdad650ce0e14e721a00062912aa1cdf26147f74

2022-05-31 11:54 UTC, kaechele commented on packages/config/config/devices/0x027a/templates/zooz_template.json
>  		"label": "Smart Bulb Mode: Dimming Reporting Behavior",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/cdad650ce0e14e721a00062912aa1cdf26147f74

2022-05-31 12:03 UTC, kaechele commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"description": "Disables inclusion/exclusion commands on paddle for use with scene controls."
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/4f0f40de355fda43279a6d92643423d2c6b474c4

2022-05-31 12:13 UTC, kaechele commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"description": "Disables inclusion/exclusion commands on paddle for use with scene controls."
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/4f0f40de355fda43279a6d92643423d2c6b474c4

2022-05-31 12:14 UTC, kaechele commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"description": "Send command to associated device.",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/cf96d6e83b7920f76dd341642fa22339c77bd2eb

2022-05-31 13:04 UTC, kaechele commented on packages/config/config/devices/0x027a/zen20.json
> +			"label": "CH1 Auto Turn-Off Setting"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/85a100ec2b2dae8f665e6bd260a88e8f428c0f9e

2022-05-31 13:10 UTC, kaechele commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN1. Choose the input/switch type you want to connect to the IN1 terminal. Default: momentary switch"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/d2ded72fe905cd51e3b710136d727309dbe8b5f7

2022-05-31 13:10 UTC, kaechele commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN2. Choose the input/switch type you want to connect to the IN2 terminal. Default: momentary switch"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/d2ded72fe905cd51e3b710136d727309dbe8b5f7

2022-05-31 13:10 UTC, kaechele commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN3. Choose the input/switch type you want to connect to the IN3 terminal. Default: momentary switch"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/d2ded72fe905cd51e3b710136d727309dbe8b5f7

2022-05-31 13:10 UTC, kaechele commented on packages/config/config/devices/0x027a/zen31.json
> +			"description": "Switch / Input Type for IN4. Choose the input/switch type you want to connect to the IN4 terminal. Default: momentary switch"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/d2ded72fe905cd51e3b710136d727309dbe8b5f7

2022-05-31 13:10 UTC, kaechele commented on packages/config/config/devices/0x027a/zse08.json
>  			"description": "The value that will be set when the sensor is triggered",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/d2ded72fe905cd51e3b710136d727309dbe8b5f7

2022-05-31 14:28 UTC, AlCalzone commented on packages/config/config/devices/templates/master_template.json
> +		"defaultValue": 1,
Oh, right. Okay then

2022-05-31 15:23 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/2",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:23 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"label": "Switch 3: Type"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:23 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"description": "Sets the time after which relay 1 turns off once it has been turned on. Using the units defined in parameter 15."
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:24 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/12",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:24 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/12",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:24 UTC, kaechele commented on packages/config/config/devices/0x027a/zen16.json
> +			"$import": "#paramInformation/15",
Kept it. https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:24 UTC, kaechele commented on packages/config/config/devices/0x027a/zen17.json
> +			"$import": "#paramInformation/2",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/1d1ee155b3816d1f1c8c92b4c1712c7304baf4fc

2022-05-31 15:33 UTC, kaechele commented on packages/config/config/devices/0x027a/zse41.json
> +			"description": "When enabled, the device will report open when the magnet is near"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/39f878cf417cc8aac562f70212ced00f0ad35909

2022-05-31 15:40 UTC, kaechele commented on packages/config/config/devices/0x027a/zen32.json
> +			"description": "Determines whether an on/off report is sent and LED changes on button press, when the relay is disabled"
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/0474898009b11dd31e798ffd75ed7c752783e890

2022-05-31 15:44 UTC, kaechele commented on packages/config/config/devices/0x027a/zen30.json
> +			"description": "Brightness level for the dimmer to come on to at single tap.",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/4664ce1eeb27ca69e87ea435140efac7f5fa099b

2022-05-31 15:45 UTC, kaechele commented on packages/config/config/devices/0x027a/zen25.json
> +			"unit": "Amperes",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/30fb7a09f519e28abf3f11ff520cf58254163ba2

2022-05-31 15:52 UTC, kaechele commented on packages/config/config/devices/0x027a/zen31.json
>  			"description": "Click/toggle the connected switch 1 time to trigger a scene.",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/504ab2e122c1ad4e5262500a7d4ffb87134a87e1

2022-05-31 16:00 UTC, kaechele commented on packages/config/config/devices/0x027a/zse09.json
>  			"description": "delay after motion before turning OFF",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/471315296f242e03d7aef838c7067ccea8b6459d

2022-05-31 16:00 UTC, kaechele commented on packages/config/config/devices/0x027a/zse40.json
>  			"description": "Set the trigger interval for motion sensor re-activation.",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/471315296f242e03d7aef838c7067ccea8b6459d

2022-05-31 16:06 UTC, kaechele commented on packages/config/config/devices/0x027a/zen20.json
>  			"description": "Enable / Disable Physical Button Functionality",
https://github.com/zwave-js/node-zwave-js/pull/4619/commits/4208837a5f872b0579cd2a9ba5ee54e9637ec577

2022-05-31 16:08 UTC, kaechele commented
Thanks for the review!
This is ready for re-review. Feel free to resolve/reject the newest changes.

2022-06-07 12:59 UTC, AlCalzone commented
Thanks! Hope I didn't miss anything now. For some reason Github won't let me view the discussions and the latest changes at the same time.

2022-06-07 12:59 UTC, AlCalzone approved these changes

2022-06-07 13:03 UTC, merged