feat:added ha-zw-5pa
AlCalzone/node-zwave-js pull request #4725
Opened 2022-06-20 18:27 UTC by prairieit

added ha-zw-5pa

2022-06-21 06:36 UTC, AlCalzone requested changes
Thanks, a couple of remarks

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Set Parameters 101~104 to The Default States",
```suggestion
			"label": "Set Parameters 101~104 to Default",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Time For Sending Meter Report (watt)",
```suggestion
			"label": "Meter Report Interval (W)",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +					"label": "Disabled",
```suggestion
					"label": "Disable",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Time For Sending Meter Report (kwh)",
```suggestion
			"label": "Meter Report Interval (kWh)",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Time For Sending Meter Report (voltage)",
```suggestion
			"label": "Meter Report Interval (V)",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Time For Sending Meter Report (current)",
```suggestion
			"label": "Meter Report Interval (A)",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Minimum Change in Wattage For a Meter Report",
```suggestion
			"label": "Meter Report Threshold",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
>  			"maxValue": 32767,
Are you sure about this limit? If -32768 was interpreted as unsigned before, this limit could also have been 0...65535. Please double-check if possible.

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Minimum Change in Wattage Percent For a Meter Report",
```suggestion
			"label": "Meter Report Threshold (Relative)",
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"label": "Device State After Power Failure",
Please replace this entire parameter definition with
```json
	{
		"#": "2",
		"$import": "~/templates/master_template.json#state_after_power_failure_prev_on_off"
	}
```

2022-06-21 06:36 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
> +			"description": "Allows locking or unlocking all configurations",
```suggestion
			"label": "Lock Configuration Parameters",
```

2022-06-21 15:25 UTC, CloudWrench42 commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
>  			"maxValue": 32767,
The documentation is not the most well written. This is the section for parameter 16
[Aibase Smart Plug (Z-Wave) User Guide.pdf](https://github.com/zwave-js/node-zwave-js/files/8950261/Aibase.Smart.Plug.Z-Wave.User.Guide.pdf)

> Parameter No. 16 The value here represents minimum change in wattage (in terms of
> wattage) for a meter report (watt) to be sent
> When the change value of load power exceeds the setting value, smart plug will send meter
> report (watt) to associated device (Group Lifeline).
> Possible values:
> -32768 to 32767 (0 - 65535W)
> -32768 to -1：65535 to 32768
> 1 to 32767: 1 to 32767
> 0 - The function is disabled.
> Default value: 50 (50W)
> Parameter size: 2 [byte]

2022-06-22 07:11 UTC, AlCalzone requested changes

2022-06-22 07:11 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
>  			"maxValue": 32767,
Ok, yeah that is because some hubs don't have the option to enter the value as unsigned. I'll change it.

2022-06-22 07:11 UTC, AlCalzone commented on packages/config/config/devices/0x0384/ha-zw-5pa.json
>  			"maxValue": 32767,
```suggestion
			"minValue": 0,
			"maxValue": 65535,
```

2022-06-22 07:11 UTC, AlCalzone approved these changes

2022-06-22 07:16 UTC, merged