Slightly clean up the fibaro motion sensor config
AlCalzone/node-zwave-js pull request #4790
Opened 2022-07-09 23:41 UTC by KTibow

This changes some stuff for the config in the fibaro motion sensor. Check the diff. It's still not consistent, but better than before.

2022-07-13 16:19 UTC, marcus-j-davies commented
@KTibow 

To correct correct the PR check.
Change `[fix] Slightly clean up the fibaro motion sensor config`
To : `fix(config): slightly clean up the fibaro motion sensor config`

2022-07-18 10:29 UTC, AlCalzone requested changes
I like "more consistent" than before. A few changes please to make sure at least the new changes conform to the style guide.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 3,
The range in the description does not match the range defined by min/maxValue. I'm assuming the min/max is wrong, since 0 moves doesn't make sense.
Anyways, don't mention ranges in the description unless necessary.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Amount of time (seconds) the alarm will be canceled after.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "The difference between night and day (lux), used in parameter #8.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 15,
This entire parameter should be split like here:
https://github.com/zwave-js/node-zwave-js/blob/08d01412047db027a64efbdd90521bdcf89dbc86/packages/config/config/devices/0x010f/fgd212.json#L385-L409

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Time period after which a tamper alarm will be cancelled (seconds).",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Minimum change in light intensity level resulting in illumination report (lux).",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Time interval (seconds) between consecutive illumination reports (sent even when there is no change).",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"valueSize": 2,
```suggestion
			"description": "The change in temperature resulting in temperature report",
			"valueSize": 2,
			"unit": "0.1 °C",
```

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Time interval (seconds) between consecutive temperature reports (sent even when there is no change).",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"valueSize": 2,
```suggestion
			"description": "Value added to the actual temperature",
			"valueSize": 2,
			"unit": "0.1 °C",
```

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "When the temperature is below this (°C), the light is blue.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "When the light intensity (lux) is above this, the brightness of the light is 1%.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "When the light intensity (lux) is below this, the brightness of the light is 1%.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "Percent brightness the LED lights up to.",
Remove description and add
```
"unit": "%",
```
please

2022-07-18 10:29 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
> +			"description": "When the temperature is above this (°C), the light is blue.",
The unit should be specified using the `"unit"` property, not as part of the description.

2022-07-18 13:27 UTC, KTibow commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 3,
This means that when it's set to 0, 1 move is required, and when it's set to 3, 4 moves are required. Should I remove it to enhance clarity?

2022-07-18 13:29 UTC, KTibow commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 15,
I don't know that much about how you go about things here, should I just copy that into here?

2022-07-18 13:40 UTC, KTibow commented
Should I work on updating the labels to be consistent, short, and use title case?

2022-07-18 15:17 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 3,
Oh, I'd model this with options (and allowManualEntry: false) then.
value 0 => label 1
value 1 => label 2
etc.

2022-07-18 15:19 UTC, AlCalzone commented on packages/config/config/devices/0x010f/fgms001.json
>  			"maxValue": 15,
yeah you can basically copy this part, but update the firmwareVersion condition and the parameter no (27 should be 18 here)

2022-07-18 15:20 UTC, AlCalzone commented
> Should I work on updating the labels to be consistent, short, and use title case?

Yeah, If you don't mind. I know this was meant as a partial improvement.

2022-07-26 09:28 UTC, AlCalzone approved these changes
Far from perfect, but better than before 😅

2022-07-26 09:35 UTC, merged