feat(config): add GE/Jasco/Enbrighten 58438/ZWA3016
AlCalzone/node-zwave-js pull request #4913
Opened 2022-08-11 19:09 UTC by natekspencer

Add Enbrighten 58438/ZWA3016 device config file

2022-08-15 20:49 UTC, jascoproducts requested changes
Thanks for adding this and updating the template. We have some change requests on the 58438_zwa3016.json.

1. Change manufacturer to "Enbrighten"
2. Change label to "58438 / ZWA3016"
3. Change description to "In-Wall Paddle Dimmer, 700S"

2022-08-16 07:51 UTC, AlCalzone requested changes
Thanks, a few minor things

2022-08-16 07:51 UTC, AlCalzone commented on packages/config/config/devices/0x0063/templates/jasco_template.json
> +	"3way_setup": {
Lets rename this to
```suggestion
	"three_way_setup": {
```

2022-08-16 07:51 UTC, AlCalzone commented on packages/config/config/devices/0x0063/templates/jasco_template.json
> +		"description": "Set the 3-way switch configuration as add-on or standard.",
```suggestion
```
We prefer to avoid descriptions if they don't add significant value.

2022-08-16 07:51 UTC, AlCalzone commented on packages/config/config/devices/0x0063/templates/jasco_template.json
> +		"label": "LED Light Color",
We mostly use `LED Indicator`, not `LED Light` to refer to built-in LEDs. Please rename for consistency

2022-08-16 07:51 UTC, AlCalzone commented on packages/config/config/devices/0x0063/templates/jasco_template.json
> +		"label": "LED Light Intensity",
dito

2022-08-16 07:51 UTC, AlCalzone commented on packages/config/config/devices/0x0063/templates/jasco_template.json
> +		"maxValue": 7,
Does 0 equal off? Then please add a single option with the label "Off" for the value 0

2022-08-16 12:34 UTC, jascoproducts approved these changes, later dismissed

2022-08-17 07:27 UTC, AlCalzone approved these changes

2022-08-17 07:33 UTC, merged