feat(config): Zoon Zen77 New Ramp Rates
AlCalzone/node-zwave-js pull request #5006
Opened 2022-09-04 18:29 UTC by cdnninja

Adding ramp rate updates for new firmware on zooz 77. Referenced from here: 
https://www.support.getzooz.com/kb/article/550-zen77-s2-dimmer-700-advanced-settings/

2022-09-04 18:47 UTC, cdnninja commented
Ready for review. I am not sure why it isn't liking my titles though.

2022-09-12 20:32 UTC, AlCalzone requested changes
Looks good, except the labels. Those really don't match the style guide :)
Hmmm, neither does the template you copied this from - we should change that.

2022-09-12 20:32 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"label": "Dimmer on ramp rate (fade-in effect for on  operation) when operated manually",
```suggestion
		"label": "Ramp Rate On (Manual Control)",
```

2022-09-12 20:32 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"label": "Dimmer off ramp rate (fade-out effect for on  operation) when operated manually",
```suggestion
		"label": "Ramp Rate Off (Manual Control)",
```

2022-09-12 20:32 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"label": "Z-Wave Dimmer on ramp rate (fade-in effect for on zwave operation)",
```suggestion
		"label": "Ramp Rate On (Z-Wave)",
```

2022-09-12 20:32 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +		"label": "Z-Wave Dimmer off ramp rate (fade-out effect for on zwave operation)",
```suggestion
		"label": "Ramp Rate Off (Z-Wave)",
```

2022-09-12 20:32 UTC, AlCalzone commented on packages/config/config/devices/0x027a/templates/zooz_template.json
> +	"dimmer_on_ramp_rate": {
Please edit the template above this line in a similar fashion

2022-09-15 07:01 UTC, AlCalzone approved these changes

2022-09-15 07:02 UTC, AlCalzone commented
Thanks!

2022-09-15 07:11 UTC, merged