Add ZEN04 configuration
AlCalzone/node-zwave-js pull request #5043
Opened 2022-09-10 20:24 UTC by mikebaz

This change adds a configuration file for the ZEN04 smart plugs.  Values are based on the ZEN05 file and the info at https://www.support.getzooz.com/kb/article/1114-zen04-smart-plug-advanced-settings/.

2022-09-12 11:18 UTC, AlCalzone requested changes
Thanks, just a few remarks

2022-09-12 11:18 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen04.json
> +		},
This should use a template like the ZEN05 does here:
https://github.com/zwave-js/node-zwave-js/blob/81d6306c505b8af4d51ba8a10e645c6a8dd0f7a7/packages/config/config/devices/0x027a/zen05.json#L48-L51
except that you need the `..._prev_off_on` variant.

2022-09-12 11:18 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen04.json
> +			]
Please change to this for consistency:
```suggestion
		"label": "LED Indicator",
		"valueSize": 1,
		"defaultValue": 0,
		"allowManualEntry": false,
		"options": [
			{
				"label": "On when load is on",
				"value": 0
			},
			{
				"label": "On when load is off",
				"value": 1
			},
			{
				"label": "Always off",
				"value": 2
			},
			{
				"label": "Always on",
				"value": 3
			}
		]
```

2022-09-12 11:18 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen04.json
> +		},
These don't need the label specified again, it comes from the template

2022-09-12 11:18 UTC, AlCalzone commented on packages/config/config/devices/0x027a/zen04.json
> +			]
(looks like I messed up the indentation, but the bot will correct that)

2022-09-12 14:10 UTC, mikebaz commented
ok, I believe I correctly implemented the requested changes.  Sorry for not getting it right the first time - I know that wastes time on your end. :(

2022-09-12 20:18 UTC, AlCalzone commented
All good - this was one of the better PRs ;)
Our standards are pretty high, so it's not easy to fulfill them.

2022-09-12 20:18 UTC, AlCalzone approved these changes

2022-09-12 20:18 UTC, merged

2022-09-17 01:47 UTC, gminco commented
Could we be missing one extra parameter?
I see 8 on the Zooz site but after including one I'm counting 9:
![image](https://user-images.githubusercontent.com/96509060/190835794-b3136999-692d-446c-bb38-b0b456d15e25.png)

2022-09-17 02:47 UTC, gminco commented
I've tried but I cannot edit the file, all it needs is this to be added:

`,
		{
			"#": "9",
			"$import": "templates/zooz_template.json#led_indicator_brightness"
		}`

2022-09-19 09:26 UTC, AlCalzone commented
@gminco I cannot find parameter 9 in [Zooz's documentation](https://www.support.getzooz.com/kb/article/1114-zen04-smart-plug-advanced-settings/). If it is actually missing, please open a new issue and share the manual or whatever states that it does exist.

2022-09-19 11:35 UTC, gminco commented
@AlCalzone it's on the documentation link you provided, but it's between parameter 1 and 2.

2022-09-19 12:22 UTC, mikebaz commented
@gminco ah you're right, I missed that.  as mentioned the update requires a new PR.  I'll get one in shortly.