feat(config): add params, metadata, associations to Merten 507801
AlCalzone/node-zwave-js pull request #5478
Opened 2023-02-17 16:42 UTC by willmakenoise

Filled in config file with missing data.

Added params: 176, 177, 178, 179, 180.
Added metadata.
Renamed association to reflect actual functionality of the group.

The association is only sending Basic_Window_Covering commands, so it can not be used as a lifeline. It will only control other devices supporting this command class.

2023-02-20 14:28 UTC, AlCalzone requested changes
Thanks, a few changes please. About the association I'm not sure - I suppose some users would like to get the commands to have some kind of state in their home automation system. `isLifeline` enables just that. Of course this means I'd have to add support for that CC to Z-Wave JS first.

Side note: I wonder who thought it would be a good idea to split the input into two parameters instead of just using a 2-byte param 🤷‍♂️

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"description": "Changeover delay",
```suggestion
			"label": "Changeover Delay",
			"description": "For motor protection",
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"unit": "25 seconds",
```suggestion
			"unit": "25.6 seconds",
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"unit": "25 seconds",
```suggestion
			"unit": "25.6 seconds",
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"description": "Input 1.",
```suggestion
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"description": "Input 2.",
```suggestion
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"description": "Input 1.",
```suggestion
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +			"description": "Input 2.",
```suggestion
```

2023-02-20 14:28 UTC, AlCalzone commented on packages/config/config/devices/0x007a/507801.json
> +		"reset": "Tripple click button, then click and hold for 5 seconds",
```suggestion
		"reset": "Triple click button, then click and hold for 5 seconds",
```

2023-02-20 23:38 UTC, willmakenoise commented
Thanks for the feedback!

I was unsure about the is_lifeline parameter, because of the lack of command class support.
At this point it might be confusing to the user, because it will have no effect. 
But I'll change it, and I hope you can implement the command class at some point. It is very similar to multilevel switch.. so might not be too much work?
I would have done it myself, but at this point I don't know the code base well enough. 

These Merten devices are very poorly implemented. It seems that they just wanted to be able to slap the Z-Wave logo on the device, without following the protocol. There are so many quirks with their devices, and support fully ended when Schneider bought Merten years ago. 
Notice the manufacturer ID.. one of the real early ones ;) 

You should see the parameters for their wall switches.. it's horrible. Real smart devs 🤓

2023-03-01 11:26 UTC, willmakenoise commented
@AlCalzone Anything else I should do on this? Or is it good to be merged?

2023-03-06 15:26 UTC, AlCalzone approved these changes

2023-03-06 15:27 UTC, merged