feat: new configuration for ad370 device
AlCalzone/node-zwave-js pull request #5590
Opened 2023-03-18 20:12 UTC by kimjohnsson

2023-03-29 23:08 UTC, kimjohnsson commented
The z-wave alliance doesn't specify a Product Type ID for this device.. How do I handle that? I put the `productType` same as `productId` but not sure this is right...

2023-04-17 15:04 UTC, AlCalzone commented
If you use Z-Wave JS UI, it should show you the full ID when you open the node "dropdown".

2023-04-17 15:08 UTC, AlCalzone requested changes
This does not match our style guide, especially regarding labels and descriptions (which we avoid in favor of more useful properties like unit, options, ...).

Please give https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide?id=labels (and the following sections) a good read and apply it throughout.

2023-04-17 15:08 UTC, AlCalzone commented on packages/config/config/devices/0x0060/ad370.json
> +			"zwaveAllianceId": [4514, 4648]
According to the ZWA website, these are two different manufacturers (Everspring and NEXA). Do you know if they use the same IDs? Often those re-branded devices end up with a different manufacturer ID or so.

2023-04-17 15:08 UTC, AlCalzone commented on packages/config/config/devices/0x0060/ad370.json
> +			"description": "Def 0",
Unnnecessary description.

2023-04-17 15:08 UTC, AlCalzone commented on packages/config/config/devices/0x0060/ad370.json
> +			"description": "Def 0, second",
Unnnecessary description. Units should be provided via the `unit` property.

2023-04-17 15:08 UTC, AlCalzone commented on packages/config/config/devices/0x0060/ad370.json
> +			"description": "Def 2",
Is there an explanation for the values? Those should probably be `options`.

2023-04-17 15:08 UTC, AlCalzone commented on packages/config/config/devices/0x0060/ad370.json
> +			"description": "0: unknow, 1:2 wire, 2:3 wire",
This should be converted to options.

2024-07-10 10:02 UTC, closed without merging