feat(config): add/fix params for Intermatic PE653
AlCalzone/node-zwave-js pull request #5822
Opened 2023-05-19 22:54 UTC by philh30

Fix params 1, 2 & 22 and add params 3-21, 23, 32-47, 49-50 for Intermatic PE653.

2023-05-22 11:04 UTC, AlCalzone requested changes
Thanks. A couple of remarks

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"label": "Booster (Cleaner) Pump Installed",
This sounds like a readonly param. Is it?

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Minimum time pump will continue to run after heater shutoff for cooldown. Circuit 5 will be assigned to the heater if >=0. Set to -1 to disable.",
Not sure if "Fireman Timeout" is a commonly used expression. Maybe there's a better label which also makes the description unnecessary?

"Set to -1 to disable" should be removed and instead merged with the label for that option.

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +					"label": "No heater installed",
```suggestion
					"label": "Disable / No heater installed",
```
maybe?

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Temperature at air/freeze sensor when freeze protection starts. Set to 0 to disable freeze protection.",
The description seems unnecessary. Also is the user meant to enter any other values than 0, 40-44? If not, add `"allowManualEntry": false`

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Turn on the circuit when system is in freeze protection mode. Requires connected air/freeze sensor.",
How about this?
```suggestion
			"label": "Freeze Protection: Turn On Circuit 1",
			"description": "Requires connected air/freeze sensor.",
```
with 5 identical parameters, the alternative would end up cluttering UIs a lot.

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"label": "Freeze Protection: Circuit 2"
If we do this, give all partial params for 50 the same treatment.

2023-05-22 11:04 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Start time (first two bytes, little endian) and stop time (last two bytes, little endian) of schedule in minutes past midnight, e.g. 12:05am (0x0500) to 3:00pm (0x8403) is entered
These will be a lot of repeated and long descriptions. Maybe the other descriptions should just refer to this one?

2023-05-22 12:26 UTC, philh30 commented on packages/config/config/devices/0x0005/pe653.json
> +			"label": "Booster (Cleaner) Pump Installed",
It should be, but it isn't. Its value needs to be linked to 1[0xff00] to work properly - disabled when 1[0xff00] is disabled and enabled when 1[0xff00] has a circuit/pump speed selected. The PE653 will accept a mismatch though, and having 1[0x01] disabled will block the pump speed in 1[0xff00] from operating. I'm not sure if there are any ill effects from having 1[0x01] enabled while 1[0xff00] is disabled.

The handheld PE953 controller that ships with the PE653 doesn't expose this as a separate config option to the user, and just handles the logic to tie this to 1[0xff00].

2023-05-22 13:00 UTC, AlCalzone commented on packages/config/config/devices/0x0005/pe653.json
> +			"label": "Booster (Cleaner) Pump Installed",
got it

2023-05-22 22:33 UTC, philh30 commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Minimum time pump will continue to run after heater shutoff for cooldown. Circuit 5 will be assigned to the heater if >=0. Set to -1 to disable.",
Good point. "Fireman Timeout" makes some sense in that it's controlling the fireman switch on the heater, but "Heater Cooldown Period" would be more descriptive. I think "Set to -1 to disable" can be skipped on the option label as "No heater installed" should be descriptive enough.

2023-05-22 22:35 UTC, philh30 commented on packages/config/config/devices/0x0005/pe653.json
> +			"description": "Temperature at air/freeze sensor when freeze protection starts. Set to 0 to disable freeze protection.",
Agreed on the description - will remove.

The allowable values are just 0, 40-44. The `base_options_nounit` template provides `"allowManualEntry": false` so it's not necessary here.

2023-05-22 23:46 UTC, philh30 commented on packages/config/config/devices/0x0005/pe653.json
> +					"label": "No heater installed",
As noted above, I think we can skip this as "No heater installed" should be sufficient.

2023-05-22 23:47 UTC, philh30 commented
@AlCalzone I think I've addressed everything, but let me know if there are additional changes you'd like to see. Thanks for the review!

2023-07-11 09:19 UTC, AlCalzone approved these changes

2023-07-11 09:20 UTC, AlCalzone commented
closing and re-opening to trigger tests

2023-07-11 09:27 UTC, merged