Fix for issue 6509 - Strips Drip 700 Configurations related.
AlCalzone/node-zwave-js pull request #6514
Opened 2023-11-23 09:06 UTC by dparyani

Fix for issue 6509.

Following discrepancies have been corrected:
1. Label for config parameter 4
2. Config parameter size for parameters 7 & 8

2023-11-23 09:44 UTC, AlCalzone requested changes

2023-11-23 09:44 UTC, AlCalzone commented on packages/config/config/devices/0x019a/11_04_21_22_28.json
> +			"label": "Temperature reporting type",
```suggestion
			"label": "Temperature Reporting",
```

2023-11-23 10:00 UTC, dparyani commented on packages/config/config/devices/0x019a/11_04_21_22_28.json
> +			"label": "Temperature reporting type",
Updated. Thank you!

2024-04-02 11:02 UTC, AlCalzone approved these changes

2024-04-02 11:03 UTC, merged