feat(config): init for gdzw7-eco
AlCalzone/node-zwave-js pull request #6572
Opened 2023-12-27 21:34 UTC by zackbcom

## Changes
- Added config for [
GDZW7-ECO - Ecolink 700 Series Garage Door Controller ](https://products.z-wavealliance.org/products/4475)
- Params from debug and product manual. 
- [gdzw7-eco_debug.json](https://github.com/zwave-js/node-zwave-js/files/13781675/gdzw7-eco_debug.json)

2024-01-01 22:38 UTC, zackbcom commented
@AlCalzone What is the best way to test configs on the ui?

I'm running [zwave-js-ui](https://github.com/zwave-js/zwave-js-ui) on a docker container. Am I able to copy the configs into the container and re-integrate the device to test these changes? Do you know the location if that is the easiest way?

Thanks.

2024-02-10 07:07 UTC, zackbcom commented
@AlCalzone ready for review

2024-04-04 12:05 UTC, AlCalzone requested changes
Sorry for the delay - I just got back from parental leave. I'd have fixed this myself, but the comments about the defaults left me confused...
What are the default values the device has when freshly reset and paired? The ones in the JSON file or the ones in the comments behind them?

Other than that I have a few minor remarks:

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +	},
This can probably be removed, since 700 series devices MUST support the Association Group Information CC.

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"description": "Unattended close operation wait period in seconds.",
We avoid descriptions that merely restate the information from the label and other parameter metadata. I suppose changing the label slightly makes the description unnecessary:
```suggestion
			"label": "Unattended Close Wait Period",
```

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"description": "Number of milliseconds to turn on relay switch for.",
Dito
```suggestion
			"label": "Relay Turn On Duration",
```

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"description": "Accelerometer vibration detection sensitivity: 1 is least sensitive, 100 is most sensitive.",
```suggestion
			"description": "1 is least sensitive, 100 is most sensitive.",
```

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"description": "Number of attempts on top of the stack-level retries to try to reach the controller/hub with Z-Wave messages.",
I don't think most users understand this description. I'd just remove it.

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"unit": "attempts",
Unit can be removed too.

2024-04-04 12:05 UTC, AlCalzone commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +		},
Both descriptions are unnecessary.

2024-04-11 02:28 UTC, zackbcom commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +	},
removed `associations`

2024-04-11 02:28 UTC, zackbcom commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"unit": "attempts",
removed `unit`

2024-04-11 02:29 UTC, zackbcom commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +		},
removed `descriptions`

2024-04-11 02:29 UTC, zackbcom commented on packages/config/config/devices/0x014a/gdzw7-eco.json
> +			"description": "Number of attempts on top of the stack-level retries to try to reach the controller/hub with Z-Wave messages.",
removed `description`

2024-04-11 02:30 UTC, zackbcom commented
> Sorry for the delay - I just got back from parental leave. I'd have fixed this myself, but the comments about the defaults left me confused... What are the default values the device has when freshly reset and paired? The ones in the JSON file or the ones in the comments behind them?
> 
> Other than that I have a few minor remarks:

I have updated the default values to the one from the device firmware. The others were from the manual, which i have removed.

2024-07-10 07:52 UTC, AlCalzone approved these changes
I've removed the templates again, we're trying to get away from the super-generic ones that just specify a range.

2024-07-10 07:53 UTC, merged