feat(config): modify UltraPro 700 Z-Wave Switch
AlCalzone/node-zwave-js pull request #6726
Opened 2024-04-04 18:58 UTC by apella12

Messed up the other one trying to rebase. Just picked the changed file.
Signed-off-by: Bob Eckhoff <katmandodo@yahoo.com>

PR description here

2024-04-06 02:43 UTC, kpine commented
The newer Jasco switches support Central Scene, so is it necessary to continue adding Group 2 automatically for double presses?

2024-04-07 13:08 UTC, apella12 commented
@kpine Don't know. Don't have the device, just trying to help a bit on the `Config` backlog with the parental leave. The ZWA link that the person who asked for this posted still shows Association Group 3 for double taps. 

On the original post (before my failed rebase attempt) @AlCalzone asked @jascoproducts for comment, but they never did, so maybe they can answer your question?

Lastly there are a number of Jasco stubs without groups or parameters that Jasco could help with if they were so inclined.

2024-04-08 15:36 UTC, jascoproducts commented
58433 and 59344 are indeed the same device. 59344 is actually a 2 pack SKU of 58433, so not sure why that is showing up.

Configuration parameters are correct, thanks for adding those.

2024-04-08 15:39 UTC, jascoproducts commented
On second thought I believe we are leaving the multipack SKUs attached to their relevant child SKUs for easier identification. Fine to leave 59344 in there as-is.

2024-04-08 15:48 UTC, kpine commented
> still shows Association Group 3 for double taps.

I was not commenting on the definition of the group (that is fine), but the part where the group is added automatically via `"isLifeline": true`. When this is true the association is setup automatically and users are unable to remove it except temporarily (a re-interview will re-add it). I assume (I don't have a newer version either) double taps will send two messages for each double-press: Basic Set and Central Scene Event, with no way to disable that.

Just a general question for this project as newer Jasco switches that support Central Scene are added.

2024-04-08 16:38 UTC, AlCalzone commented
We should prefer the Central Scene variant over the Basic Set "lifeline" where possible.
Maybe best to start without the lifeline on new devices and add it only when necessary.

2024-04-09 07:15 UTC, AlCalzone requested changes

2024-04-09 07:15 UTC, AlCalzone commented on packages/config/config/devices/0x0063/58433_59344_zwa4011.json
> +		// Needed for double-tap support
```suggestion
		// Enables Basic Set via Group 3 as an alternative way to detect double taps (instead of Central Scene)
```

2024-04-09 07:15 UTC, AlCalzone approved these changes

2024-04-09 07:20 UTC, merged