feat(config): add Lockly Secure Plus
AlCalzone/node-zwave-js pull request #7382
Opened 2024-11-09 05:16 UTC by james-cc

Fixes: #7223 

The manual linked in the issue seems to indicate the same model name has two different device ids

2024-11-13 18:16 UTC, james-cc commented
Could you take a look when you get the chance, @AlCalzone?

2025-01-10 13:02 UTC, AlCalzone requested changes
Sorry for the delay!

2025-01-10 13:02 UTC, AlCalzone commented on packages/config/config/devices/0x043d/pgd728f_zpu.json
> +			"label": "Activated or Deactivated Fp Module"
This should just use the `base_enable_disable` template or the inverted version and label `Fingerprint Module`.

2025-01-10 13:02 UTC, AlCalzone commented on packages/config/config/devices/0x043d/templates/lockly_template.json
> +		]
What do you mean by this seems flipped? Is the fingerprint module active when the value is 0 or not?

2025-01-14 05:23 UTC, james-cc commented on packages/config/config/devices/0x043d/pgd728f_zpu.json
> +			"label": "Activated or Deactivated Fp Module"
Removed device-specific template.

2025-01-14 05:25 UTC, james-cc commented on packages/config/config/devices/0x043d/templates/lockly_template.json
> +		]
Sorry, just generally meant one would expect non-inverted binary values (1 for enabled and 0 for disabled).

2025-01-15 19:26 UTC, AlCalzone commented on packages/config/config/devices/0x043d/templates/lockly_template.json
> +		]
Ah, no this is unfortunately normal. Some manufacturers do it one way, some the other way, some use both.

2025-03-11 13:08 UTC, AlCalzone approved these changes

2025-03-11 13:11 UTC, merged

2025-03-12 02:50 UTC, samrocketman commented
Thanks!  I look forward to the next update.